// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: billing.proto

package billingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_GetBalance_FullMethodName             = "/billing.v1.BillingService/GetBalance"
	BillingService_ChargeMessage_FullMethodName          = "/billing.v1.BillingService/ChargeMessage"
	BillingService_ChargeMessageDual_FullMethodName      = "/billing.v1.BillingService/ChargeMessageDual"
	BillingService_AddCredits_FullMethodName             = "/billing.v1.BillingService/AddCredits"
	BillingService_DeductCredits_FullMethodName          = "/billing.v1.BillingService/DeductCredits"
	BillingService_GetTransactionHistory_FullMethodName  = "/billing.v1.BillingService/GetTransactionHistory"
	BillingService_GetPricingRules_FullMethodName        = "/billing.v1.BillingService/GetPricingRules"
	BillingService_CreatePricingRule_FullMethodName      = "/billing.v1.BillingService/CreatePricingRule"
	BillingService_TransferBalance_FullMethodName        = "/billing.v1.BillingService/TransferBalance"
	BillingService_FreezeAccount_FullMethodName          = "/billing.v1.BillingService/FreezeAccount"
	BillingService_UnfreezeAccount_FullMethodName        = "/billing.v1.BillingService/UnfreezeAccount"
	BillingService_SetCreditLimit_FullMethodName         = "/billing.v1.BillingService/SetCreditLimit"
	BillingService_SetLowBalanceThreshold_FullMethodName = "/billing.v1.BillingService/SetLowBalanceThreshold"
	BillingService_ListBalances_FullMethodName           = "/billing.v1.BillingService/ListBalances"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BillingService предоставляет методы для работы с биллингом
type BillingServiceClient interface {
	// GetBalance получает баланс клиента
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	// ChargeMessage списывает средства за сообщение
	ChargeMessage(ctx context.Context, in *ChargeMessageRequest, opts ...grpc.CallOption) (*ChargeMessageResponse, error)
	// ChargeMessageDual атомарно списывает средства с субаккаунта и агрегатора
	// за одно SMS, инкрементит квоту агрегатора, пишет margin log.
	// Идемпотентно по idempotency_key.
	ChargeMessageDual(ctx context.Context, in *ChargeMessageDualRequest, opts ...grpc.CallOption) (*ChargeMessageDualResponse, error)
	// AddCredits добавляет средства на счет клиента
	AddCredits(ctx context.Context, in *AddCreditsRequest, opts ...grpc.CallOption) (*AddCreditsResponse, error)
	// DeductCredits списывает средства со счета клиента
	DeductCredits(ctx context.Context, in *DeductCreditsRequest, opts ...grpc.CallOption) (*DeductCreditsResponse, error)
	// GetTransactionHistory получает историю транзакций
	GetTransactionHistory(ctx context.Context, in *GetTransactionHistoryRequest, opts ...grpc.CallOption) (*GetTransactionHistoryResponse, error)
	// GetPricingRules получает правила тарификации для клиента
	GetPricingRules(ctx context.Context, in *GetPricingRulesRequest, opts ...grpc.CallOption) (*GetPricingRulesResponse, error)
	// CreatePricingRule создает правило тарификации
	CreatePricingRule(ctx context.Context, in *CreatePricingRuleRequest, opts ...grpc.CallOption) (*CreatePricingRuleResponse, error)
	// TransferBalance переводит средства между клиентами
	TransferBalance(ctx context.Context, in *TransferBalanceRequest, opts ...grpc.CallOption) (*TransferBalanceResponse, error)
	// FreezeAccount замораживает счет клиента
	FreezeAccount(ctx context.Context, in *FreezeAccountRequest, opts ...grpc.CallOption) (*FreezeAccountResponse, error)
	// UnfreezeAccount размораживает счет клиента
	UnfreezeAccount(ctx context.Context, in *UnfreezeAccountRequest, opts ...grpc.CallOption) (*UnfreezeAccountResponse, error)
	// SetCreditLimit устанавливает кредитный лимит для клиента
	SetCreditLimit(ctx context.Context, in *SetCreditLimitRequest, opts ...grpc.CallOption) (*SetCreditLimitResponse, error)
	// SetLowBalanceThreshold устанавливает порог низкого баланса
	SetLowBalanceThreshold(ctx context.Context, in *SetLowBalanceThresholdRequest, opts ...grpc.CallOption) (*SetLowBalanceThresholdResponse, error)
	// ListBalances получает список балансов с фильтрацией
	ListBalances(ctx context.Context, in *ListBalancesRequest, opts ...grpc.CallOption) (*ListBalancesResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, BillingService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ChargeMessage(ctx context.Context, in *ChargeMessageRequest, opts ...grpc.CallOption) (*ChargeMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChargeMessageResponse)
	err := c.cc.Invoke(ctx, BillingService_ChargeMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ChargeMessageDual(ctx context.Context, in *ChargeMessageDualRequest, opts ...grpc.CallOption) (*ChargeMessageDualResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChargeMessageDualResponse)
	err := c.cc.Invoke(ctx, BillingService_ChargeMessageDual_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) AddCredits(ctx context.Context, in *AddCreditsRequest, opts ...grpc.CallOption) (*AddCreditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCreditsResponse)
	err := c.cc.Invoke(ctx, BillingService_AddCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) DeductCredits(ctx context.Context, in *DeductCreditsRequest, opts ...grpc.CallOption) (*DeductCreditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductCreditsResponse)
	err := c.cc.Invoke(ctx, BillingService_DeductCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetTransactionHistory(ctx context.Context, in *GetTransactionHistoryRequest, opts ...grpc.CallOption) (*GetTransactionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionHistoryResponse)
	err := c.cc.Invoke(ctx, BillingService_GetTransactionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetPricingRules(ctx context.Context, in *GetPricingRulesRequest, opts ...grpc.CallOption) (*GetPricingRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPricingRulesResponse)
	err := c.cc.Invoke(ctx, BillingService_GetPricingRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CreatePricingRule(ctx context.Context, in *CreatePricingRuleRequest, opts ...grpc.CallOption) (*CreatePricingRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePricingRuleResponse)
	err := c.cc.Invoke(ctx, BillingService_CreatePricingRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) TransferBalance(ctx context.Context, in *TransferBalanceRequest, opts ...grpc.CallOption) (*TransferBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferBalanceResponse)
	err := c.cc.Invoke(ctx, BillingService_TransferBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) FreezeAccount(ctx context.Context, in *FreezeAccountRequest, opts ...grpc.CallOption) (*FreezeAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreezeAccountResponse)
	err := c.cc.Invoke(ctx, BillingService_FreezeAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) UnfreezeAccount(ctx context.Context, in *UnfreezeAccountRequest, opts ...grpc.CallOption) (*UnfreezeAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfreezeAccountResponse)
	err := c.cc.Invoke(ctx, BillingService_UnfreezeAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) SetCreditLimit(ctx context.Context, in *SetCreditLimitRequest, opts ...grpc.CallOption) (*SetCreditLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCreditLimitResponse)
	err := c.cc.Invoke(ctx, BillingService_SetCreditLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) SetLowBalanceThreshold(ctx context.Context, in *SetLowBalanceThresholdRequest, opts ...grpc.CallOption) (*SetLowBalanceThresholdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLowBalanceThresholdResponse)
	err := c.cc.Invoke(ctx, BillingService_SetLowBalanceThreshold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ListBalances(ctx context.Context, in *ListBalancesRequest, opts ...grpc.CallOption) (*ListBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBalancesResponse)
	err := c.cc.Invoke(ctx, BillingService_ListBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility.
//
// BillingService предоставляет методы для работы с биллингом
type BillingServiceServer interface {
	// GetBalance получает баланс клиента
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	// ChargeMessage списывает средства за сообщение
	ChargeMessage(context.Context, *ChargeMessageRequest) (*ChargeMessageResponse, error)
	// ChargeMessageDual атомарно списывает средства с субаккаунта и агрегатора
	// за одно SMS, инкрементит квоту агрегатора, пишет margin log.
	// Идемпотентно по idempotency_key.
	ChargeMessageDual(context.Context, *ChargeMessageDualRequest) (*ChargeMessageDualResponse, error)
	// AddCredits добавляет средства на счет клиента
	AddCredits(context.Context, *AddCreditsRequest) (*AddCreditsResponse, error)
	// DeductCredits списывает средства со счета клиента
	DeductCredits(context.Context, *DeductCreditsRequest) (*DeductCreditsResponse, error)
	// GetTransactionHistory получает историю транзакций
	GetTransactionHistory(context.Context, *GetTransactionHistoryRequest) (*GetTransactionHistoryResponse, error)
	// GetPricingRules получает правила тарификации для клиента
	GetPricingRules(context.Context, *GetPricingRulesRequest) (*GetPricingRulesResponse, error)
	// CreatePricingRule создает правило тарификации
	CreatePricingRule(context.Context, *CreatePricingRuleRequest) (*CreatePricingRuleResponse, error)
	// TransferBalance переводит средства между клиентами
	TransferBalance(context.Context, *TransferBalanceRequest) (*TransferBalanceResponse, error)
	// FreezeAccount замораживает счет клиента
	FreezeAccount(context.Context, *FreezeAccountRequest) (*FreezeAccountResponse, error)
	// UnfreezeAccount размораживает счет клиента
	UnfreezeAccount(context.Context, *UnfreezeAccountRequest) (*UnfreezeAccountResponse, error)
	// SetCreditLimit устанавливает кредитный лимит для клиента
	SetCreditLimit(context.Context, *SetCreditLimitRequest) (*SetCreditLimitResponse, error)
	// SetLowBalanceThreshold устанавливает порог низкого баланса
	SetLowBalanceThreshold(context.Context, *SetLowBalanceThresholdRequest) (*SetLowBalanceThresholdResponse, error)
	// ListBalances получает список балансов с фильтрацией
	ListBalances(context.Context, *ListBalancesRequest) (*ListBalancesResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedBillingServiceServer) ChargeMessage(context.Context, *ChargeMessageRequest) (*ChargeMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChargeMessage not implemented")
}
func (UnimplementedBillingServiceServer) ChargeMessageDual(context.Context, *ChargeMessageDualRequest) (*ChargeMessageDualResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChargeMessageDual not implemented")
}
func (UnimplementedBillingServiceServer) AddCredits(context.Context, *AddCreditsRequest) (*AddCreditsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCredits not implemented")
}
func (UnimplementedBillingServiceServer) DeductCredits(context.Context, *DeductCreditsRequest) (*DeductCreditsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductCredits not implemented")
}
func (UnimplementedBillingServiceServer) GetTransactionHistory(context.Context, *GetTransactionHistoryRequest) (*GetTransactionHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactionHistory not implemented")
}
func (UnimplementedBillingServiceServer) GetPricingRules(context.Context, *GetPricingRulesRequest) (*GetPricingRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPricingRules not implemented")
}
func (UnimplementedBillingServiceServer) CreatePricingRule(context.Context, *CreatePricingRuleRequest) (*CreatePricingRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePricingRule not implemented")
}
func (UnimplementedBillingServiceServer) TransferBalance(context.Context, *TransferBalanceRequest) (*TransferBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferBalance not implemented")
}
func (UnimplementedBillingServiceServer) FreezeAccount(context.Context, *FreezeAccountRequest) (*FreezeAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FreezeAccount not implemented")
}
func (UnimplementedBillingServiceServer) UnfreezeAccount(context.Context, *UnfreezeAccountRequest) (*UnfreezeAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnfreezeAccount not implemented")
}
func (UnimplementedBillingServiceServer) SetCreditLimit(context.Context, *SetCreditLimitRequest) (*SetCreditLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCreditLimit not implemented")
}
func (UnimplementedBillingServiceServer) SetLowBalanceThreshold(context.Context, *SetLowBalanceThresholdRequest) (*SetLowBalanceThresholdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLowBalanceThreshold not implemented")
}
func (UnimplementedBillingServiceServer) ListBalances(context.Context, *ListBalancesRequest) (*ListBalancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBalances not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}
func (UnimplementedBillingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call panics, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ChargeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ChargeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ChargeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ChargeMessage(ctx, req.(*ChargeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ChargeMessageDual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeMessageDualRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ChargeMessageDual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ChargeMessageDual_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ChargeMessageDual(ctx, req.(*ChargeMessageDualRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_AddCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).AddCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_AddCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).AddCredits(ctx, req.(*AddCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_DeductCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).DeductCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_DeductCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).DeductCredits(ctx, req.(*DeductCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetTransactionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetTransactionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetTransactionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetTransactionHistory(ctx, req.(*GetTransactionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetPricingRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPricingRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetPricingRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetPricingRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetPricingRules(ctx, req.(*GetPricingRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CreatePricingRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePricingRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CreatePricingRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CreatePricingRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CreatePricingRule(ctx, req.(*CreatePricingRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_TransferBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).TransferBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_TransferBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).TransferBalance(ctx, req.(*TransferBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_FreezeAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).FreezeAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_FreezeAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).FreezeAccount(ctx, req.(*FreezeAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_UnfreezeAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfreezeAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).UnfreezeAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_UnfreezeAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).UnfreezeAccount(ctx, req.(*UnfreezeAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_SetCreditLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCreditLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).SetCreditLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_SetCreditLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).SetCreditLimit(ctx, req.(*SetCreditLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_SetLowBalanceThreshold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLowBalanceThresholdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).SetLowBalanceThreshold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_SetLowBalanceThreshold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).SetLowBalanceThreshold(ctx, req.(*SetLowBalanceThresholdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ListBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ListBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_ListBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ListBalances(ctx, req.(*ListBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.v1.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _BillingService_GetBalance_Handler,
		},
		{
			MethodName: "ChargeMessage",
			Handler:    _BillingService_ChargeMessage_Handler,
		},
		{
			MethodName: "ChargeMessageDual",
			Handler:    _BillingService_ChargeMessageDual_Handler,
		},
		{
			MethodName: "AddCredits",
			Handler:    _BillingService_AddCredits_Handler,
		},
		{
			MethodName: "DeductCredits",
			Handler:    _BillingService_DeductCredits_Handler,
		},
		{
			MethodName: "GetTransactionHistory",
			Handler:    _BillingService_GetTransactionHistory_Handler,
		},
		{
			MethodName: "GetPricingRules",
			Handler:    _BillingService_GetPricingRules_Handler,
		},
		{
			MethodName: "CreatePricingRule",
			Handler:    _BillingService_CreatePricingRule_Handler,
		},
		{
			MethodName: "TransferBalance",
			Handler:    _BillingService_TransferBalance_Handler,
		},
		{
			MethodName: "FreezeAccount",
			Handler:    _BillingService_FreezeAccount_Handler,
		},
		{
			MethodName: "UnfreezeAccount",
			Handler:    _BillingService_UnfreezeAccount_Handler,
		},
		{
			MethodName: "SetCreditLimit",
			Handler:    _BillingService_SetCreditLimit_Handler,
		},
		{
			MethodName: "SetLowBalanceThreshold",
			Handler:    _BillingService_SetLowBalanceThreshold_Handler,
		},
		{
			MethodName: "ListBalances",
			Handler:    _BillingService_ListBalances_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing.proto",
}
