// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: routing/routing.proto

package routingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoutingService_GetRoute_FullMethodName             = "/routing.v1.RoutingService/GetRoute"
	RoutingService_SelectProvider_FullMethodName       = "/routing.v1.RoutingService/SelectProvider"
	RoutingService_CreateRoute_FullMethodName          = "/routing.v1.RoutingService/CreateRoute"
	RoutingService_UpdateRoute_FullMethodName          = "/routing.v1.RoutingService/UpdateRoute"
	RoutingService_DeleteRoute_FullMethodName          = "/routing.v1.RoutingService/DeleteRoute"
	RoutingService_ListRoutes_FullMethodName           = "/routing.v1.RoutingService/ListRoutes"
	RoutingService_CreateCountry_FullMethodName        = "/routing.v1.RoutingService/CreateCountry"
	RoutingService_GetCountry_FullMethodName           = "/routing.v1.RoutingService/GetCountry"
	RoutingService_ListCountries_FullMethodName        = "/routing.v1.RoutingService/ListCountries"
	RoutingService_UpdateCountry_FullMethodName        = "/routing.v1.RoutingService/UpdateCountry"
	RoutingService_CreateOperator_FullMethodName       = "/routing.v1.RoutingService/CreateOperator"
	RoutingService_GetOperator_FullMethodName          = "/routing.v1.RoutingService/GetOperator"
	RoutingService_ListOperators_FullMethodName        = "/routing.v1.RoutingService/ListOperators"
	RoutingService_UpdateOperator_FullMethodName       = "/routing.v1.RoutingService/UpdateOperator"
	RoutingService_CreateOperatorPrefix_FullMethodName = "/routing.v1.RoutingService/CreateOperatorPrefix"
	RoutingService_ListOperatorPrefixes_FullMethodName = "/routing.v1.RoutingService/ListOperatorPrefixes"
	RoutingService_DeleteOperatorPrefix_FullMethodName = "/routing.v1.RoutingService/DeleteOperatorPrefix"
	RoutingService_ResolveOperator_FullMethodName      = "/routing.v1.RoutingService/ResolveOperator"
)

// RoutingServiceClient is the client API for RoutingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RoutingService предоставляет методы для управления маршрутизацией
type RoutingServiceClient interface {
	// GetRoute получает маршрут для сообщения
	GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error)
	// SelectProvider выбирает оптимального провайдера для маршрута
	SelectProvider(ctx context.Context, in *SelectProviderRequest, opts ...grpc.CallOption) (*SelectProviderResponse, error)
	// CreateRoute создает новое правило маршрутизации
	CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*CreateRouteResponse, error)
	// UpdateRoute обновляет правило маршрутизации
	UpdateRoute(ctx context.Context, in *UpdateRouteRequest, opts ...grpc.CallOption) (*UpdateRouteResponse, error)
	// DeleteRoute удаляет правило маршрутизации
	DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error)
	// ListRoutes получает список правил маршрутизации
	ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error)
	// Управление странами
	CreateCountry(ctx context.Context, in *CreateCountryRequest, opts ...grpc.CallOption) (*Country, error)
	GetCountry(ctx context.Context, in *GetCountryRequest, opts ...grpc.CallOption) (*Country, error)
	ListCountries(ctx context.Context, in *ListCountriesRequest, opts ...grpc.CallOption) (*ListCountriesResponse, error)
	UpdateCountry(ctx context.Context, in *UpdateCountryRequest, opts ...grpc.CallOption) (*Country, error)
	// Управление операторами
	CreateOperator(ctx context.Context, in *CreateOperatorRequest, opts ...grpc.CallOption) (*Operator, error)
	GetOperator(ctx context.Context, in *GetOperatorRequest, opts ...grpc.CallOption) (*Operator, error)
	ListOperators(ctx context.Context, in *ListOperatorsRequest, opts ...grpc.CallOption) (*ListOperatorsResponse, error)
	UpdateOperator(ctx context.Context, in *UpdateOperatorRequest, opts ...grpc.CallOption) (*Operator, error)
	// Управление префиксами операторов
	CreateOperatorPrefix(ctx context.Context, in *CreateOperatorPrefixRequest, opts ...grpc.CallOption) (*OperatorPrefix, error)
	ListOperatorPrefixes(ctx context.Context, in *ListOperatorPrefixesRequest, opts ...grpc.CallOption) (*ListOperatorPrefixesResponse, error)
	DeleteOperatorPrefix(ctx context.Context, in *DeleteOperatorPrefixRequest, opts ...grpc.CallOption) (*DeleteOperatorPrefixResponse, error)
	// Определение оператора по номеру
	ResolveOperator(ctx context.Context, in *ResolveOperatorRequest, opts ...grpc.CallOption) (*ResolveOperatorResponse, error)
}

type routingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingServiceClient(cc grpc.ClientConnInterface) RoutingServiceClient {
	return &routingServiceClient{cc}
}

func (c *routingServiceClient) GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*GetRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteResponse)
	err := c.cc.Invoke(ctx, RoutingService_GetRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) SelectProvider(ctx context.Context, in *SelectProviderRequest, opts ...grpc.CallOption) (*SelectProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectProviderResponse)
	err := c.cc.Invoke(ctx, RoutingService_SelectProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...grpc.CallOption) (*CreateRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRouteResponse)
	err := c.cc.Invoke(ctx, RoutingService_CreateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) UpdateRoute(ctx context.Context, in *UpdateRouteRequest, opts ...grpc.CallOption) (*UpdateRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRouteResponse)
	err := c.cc.Invoke(ctx, RoutingService_UpdateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteResponse)
	err := c.cc.Invoke(ctx, RoutingService_DeleteRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutesResponse)
	err := c.cc.Invoke(ctx, RoutingService_ListRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) CreateCountry(ctx context.Context, in *CreateCountryRequest, opts ...grpc.CallOption) (*Country, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Country)
	err := c.cc.Invoke(ctx, RoutingService_CreateCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) GetCountry(ctx context.Context, in *GetCountryRequest, opts ...grpc.CallOption) (*Country, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Country)
	err := c.cc.Invoke(ctx, RoutingService_GetCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ListCountries(ctx context.Context, in *ListCountriesRequest, opts ...grpc.CallOption) (*ListCountriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCountriesResponse)
	err := c.cc.Invoke(ctx, RoutingService_ListCountries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) UpdateCountry(ctx context.Context, in *UpdateCountryRequest, opts ...grpc.CallOption) (*Country, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Country)
	err := c.cc.Invoke(ctx, RoutingService_UpdateCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) CreateOperator(ctx context.Context, in *CreateOperatorRequest, opts ...grpc.CallOption) (*Operator, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operator)
	err := c.cc.Invoke(ctx, RoutingService_CreateOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) GetOperator(ctx context.Context, in *GetOperatorRequest, opts ...grpc.CallOption) (*Operator, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operator)
	err := c.cc.Invoke(ctx, RoutingService_GetOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ListOperators(ctx context.Context, in *ListOperatorsRequest, opts ...grpc.CallOption) (*ListOperatorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperatorsResponse)
	err := c.cc.Invoke(ctx, RoutingService_ListOperators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) UpdateOperator(ctx context.Context, in *UpdateOperatorRequest, opts ...grpc.CallOption) (*Operator, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operator)
	err := c.cc.Invoke(ctx, RoutingService_UpdateOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) CreateOperatorPrefix(ctx context.Context, in *CreateOperatorPrefixRequest, opts ...grpc.CallOption) (*OperatorPrefix, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperatorPrefix)
	err := c.cc.Invoke(ctx, RoutingService_CreateOperatorPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ListOperatorPrefixes(ctx context.Context, in *ListOperatorPrefixesRequest, opts ...grpc.CallOption) (*ListOperatorPrefixesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperatorPrefixesResponse)
	err := c.cc.Invoke(ctx, RoutingService_ListOperatorPrefixes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) DeleteOperatorPrefix(ctx context.Context, in *DeleteOperatorPrefixRequest, opts ...grpc.CallOption) (*DeleteOperatorPrefixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOperatorPrefixResponse)
	err := c.cc.Invoke(ctx, RoutingService_DeleteOperatorPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ResolveOperator(ctx context.Context, in *ResolveOperatorRequest, opts ...grpc.CallOption) (*ResolveOperatorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveOperatorResponse)
	err := c.cc.Invoke(ctx, RoutingService_ResolveOperator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutingServiceServer is the server API for RoutingService service.
// All implementations must embed UnimplementedRoutingServiceServer
// for forward compatibility.
//
// RoutingService предоставляет методы для управления маршрутизацией
type RoutingServiceServer interface {
	// GetRoute получает маршрут для сообщения
	GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error)
	// SelectProvider выбирает оптимального провайдера для маршрута
	SelectProvider(context.Context, *SelectProviderRequest) (*SelectProviderResponse, error)
	// CreateRoute создает новое правило маршрутизации
	CreateRoute(context.Context, *CreateRouteRequest) (*CreateRouteResponse, error)
	// UpdateRoute обновляет правило маршрутизации
	UpdateRoute(context.Context, *UpdateRouteRequest) (*UpdateRouteResponse, error)
	// DeleteRoute удаляет правило маршрутизации
	DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error)
	// ListRoutes получает список правил маршрутизации
	ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error)
	// Управление странами
	CreateCountry(context.Context, *CreateCountryRequest) (*Country, error)
	GetCountry(context.Context, *GetCountryRequest) (*Country, error)
	ListCountries(context.Context, *ListCountriesRequest) (*ListCountriesResponse, error)
	UpdateCountry(context.Context, *UpdateCountryRequest) (*Country, error)
	// Управление операторами
	CreateOperator(context.Context, *CreateOperatorRequest) (*Operator, error)
	GetOperator(context.Context, *GetOperatorRequest) (*Operator, error)
	ListOperators(context.Context, *ListOperatorsRequest) (*ListOperatorsResponse, error)
	UpdateOperator(context.Context, *UpdateOperatorRequest) (*Operator, error)
	// Управление префиксами операторов
	CreateOperatorPrefix(context.Context, *CreateOperatorPrefixRequest) (*OperatorPrefix, error)
	ListOperatorPrefixes(context.Context, *ListOperatorPrefixesRequest) (*ListOperatorPrefixesResponse, error)
	DeleteOperatorPrefix(context.Context, *DeleteOperatorPrefixRequest) (*DeleteOperatorPrefixResponse, error)
	// Определение оператора по номеру
	ResolveOperator(context.Context, *ResolveOperatorRequest) (*ResolveOperatorResponse, error)
	mustEmbedUnimplementedRoutingServiceServer()
}

// UnimplementedRoutingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutingServiceServer struct{}

func (UnimplementedRoutingServiceServer) GetRoute(context.Context, *GetRouteRequest) (*GetRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoute not implemented")
}
func (UnimplementedRoutingServiceServer) SelectProvider(context.Context, *SelectProviderRequest) (*SelectProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectProvider not implemented")
}
func (UnimplementedRoutingServiceServer) CreateRoute(context.Context, *CreateRouteRequest) (*CreateRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRoute not implemented")
}
func (UnimplementedRoutingServiceServer) UpdateRoute(context.Context, *UpdateRouteRequest) (*UpdateRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRoute not implemented")
}
func (UnimplementedRoutingServiceServer) DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRoute not implemented")
}
func (UnimplementedRoutingServiceServer) ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoutes not implemented")
}
func (UnimplementedRoutingServiceServer) CreateCountry(context.Context, *CreateCountryRequest) (*Country, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCountry not implemented")
}
func (UnimplementedRoutingServiceServer) GetCountry(context.Context, *GetCountryRequest) (*Country, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCountry not implemented")
}
func (UnimplementedRoutingServiceServer) ListCountries(context.Context, *ListCountriesRequest) (*ListCountriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCountries not implemented")
}
func (UnimplementedRoutingServiceServer) UpdateCountry(context.Context, *UpdateCountryRequest) (*Country, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCountry not implemented")
}
func (UnimplementedRoutingServiceServer) CreateOperator(context.Context, *CreateOperatorRequest) (*Operator, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOperator not implemented")
}
func (UnimplementedRoutingServiceServer) GetOperator(context.Context, *GetOperatorRequest) (*Operator, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperator not implemented")
}
func (UnimplementedRoutingServiceServer) ListOperators(context.Context, *ListOperatorsRequest) (*ListOperatorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOperators not implemented")
}
func (UnimplementedRoutingServiceServer) UpdateOperator(context.Context, *UpdateOperatorRequest) (*Operator, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOperator not implemented")
}
func (UnimplementedRoutingServiceServer) CreateOperatorPrefix(context.Context, *CreateOperatorPrefixRequest) (*OperatorPrefix, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOperatorPrefix not implemented")
}
func (UnimplementedRoutingServiceServer) ListOperatorPrefixes(context.Context, *ListOperatorPrefixesRequest) (*ListOperatorPrefixesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOperatorPrefixes not implemented")
}
func (UnimplementedRoutingServiceServer) DeleteOperatorPrefix(context.Context, *DeleteOperatorPrefixRequest) (*DeleteOperatorPrefixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOperatorPrefix not implemented")
}
func (UnimplementedRoutingServiceServer) ResolveOperator(context.Context, *ResolveOperatorRequest) (*ResolveOperatorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveOperator not implemented")
}
func (UnimplementedRoutingServiceServer) mustEmbedUnimplementedRoutingServiceServer() {}
func (UnimplementedRoutingServiceServer) testEmbeddedByValue()                        {}

// UnsafeRoutingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingServiceServer will
// result in compilation errors.
type UnsafeRoutingServiceServer interface {
	mustEmbedUnimplementedRoutingServiceServer()
}

func RegisterRoutingServiceServer(s grpc.ServiceRegistrar, srv RoutingServiceServer) {
	// If the following call panics, it indicates UnimplementedRoutingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutingService_ServiceDesc, srv)
}

func _RoutingService_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_GetRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).GetRoute(ctx, req.(*GetRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_SelectProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).SelectProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_SelectProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).SelectProvider(ctx, req.(*SelectProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_CreateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).CreateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_CreateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).CreateRoute(ctx, req.(*CreateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_UpdateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).UpdateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_UpdateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).UpdateRoute(ctx, req.(*UpdateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_DeleteRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).DeleteRoute(ctx, req.(*DeleteRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ListRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ListRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ListRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ListRoutes(ctx, req.(*ListRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_CreateCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).CreateCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_CreateCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).CreateCountry(ctx, req.(*CreateCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_GetCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).GetCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_GetCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).GetCountry(ctx, req.(*GetCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ListCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCountriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ListCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ListCountries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ListCountries(ctx, req.(*ListCountriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_UpdateCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).UpdateCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_UpdateCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).UpdateCountry(ctx, req.(*UpdateCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_CreateOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).CreateOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_CreateOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).CreateOperator(ctx, req.(*CreateOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_GetOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).GetOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_GetOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).GetOperator(ctx, req.(*GetOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ListOperators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ListOperators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ListOperators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ListOperators(ctx, req.(*ListOperatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_UpdateOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).UpdateOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_UpdateOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).UpdateOperator(ctx, req.(*UpdateOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_CreateOperatorPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOperatorPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).CreateOperatorPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_CreateOperatorPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).CreateOperatorPrefix(ctx, req.(*CreateOperatorPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ListOperatorPrefixes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperatorPrefixesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ListOperatorPrefixes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ListOperatorPrefixes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ListOperatorPrefixes(ctx, req.(*ListOperatorPrefixesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_DeleteOperatorPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOperatorPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).DeleteOperatorPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_DeleteOperatorPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).DeleteOperatorPrefix(ctx, req.(*DeleteOperatorPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ResolveOperator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ResolveOperator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ResolveOperator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ResolveOperator(ctx, req.(*ResolveOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoutingService_ServiceDesc is the grpc.ServiceDesc for RoutingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routing.v1.RoutingService",
	HandlerType: (*RoutingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoute",
			Handler:    _RoutingService_GetRoute_Handler,
		},
		{
			MethodName: "SelectProvider",
			Handler:    _RoutingService_SelectProvider_Handler,
		},
		{
			MethodName: "CreateRoute",
			Handler:    _RoutingService_CreateRoute_Handler,
		},
		{
			MethodName: "UpdateRoute",
			Handler:    _RoutingService_UpdateRoute_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _RoutingService_DeleteRoute_Handler,
		},
		{
			MethodName: "ListRoutes",
			Handler:    _RoutingService_ListRoutes_Handler,
		},
		{
			MethodName: "CreateCountry",
			Handler:    _RoutingService_CreateCountry_Handler,
		},
		{
			MethodName: "GetCountry",
			Handler:    _RoutingService_GetCountry_Handler,
		},
		{
			MethodName: "ListCountries",
			Handler:    _RoutingService_ListCountries_Handler,
		},
		{
			MethodName: "UpdateCountry",
			Handler:    _RoutingService_UpdateCountry_Handler,
		},
		{
			MethodName: "CreateOperator",
			Handler:    _RoutingService_CreateOperator_Handler,
		},
		{
			MethodName: "GetOperator",
			Handler:    _RoutingService_GetOperator_Handler,
		},
		{
			MethodName: "ListOperators",
			Handler:    _RoutingService_ListOperators_Handler,
		},
		{
			MethodName: "UpdateOperator",
			Handler:    _RoutingService_UpdateOperator_Handler,
		},
		{
			MethodName: "CreateOperatorPrefix",
			Handler:    _RoutingService_CreateOperatorPrefix_Handler,
		},
		{
			MethodName: "ListOperatorPrefixes",
			Handler:    _RoutingService_ListOperatorPrefixes_Handler,
		},
		{
			MethodName: "DeleteOperatorPrefix",
			Handler:    _RoutingService_DeleteOperatorPrefix_Handler,
		},
		{
			MethodName: "ResolveOperator",
			Handler:    _RoutingService_ResolveOperator_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "routing/routing.proto",
}
