// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: smpp.proto

package smppv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SMPPGateway_DeliverDLR_FullMethodName = "/smpp.v1.SMPPGateway/DeliverDLR"
)

// SMPPGatewayClient is the client API for SMPPGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SMPPGateway provides internal gRPC methods for SMPP gateway operations
type SMPPGatewayClient interface {
	// DeliverDLR delivers a DLR (Delivery Receipt) to a connected SMPP client
	DeliverDLR(ctx context.Context, in *DeliverDLRRequest, opts ...grpc.CallOption) (*DeliverDLRResponse, error)
}

type sMPPGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewSMPPGatewayClient(cc grpc.ClientConnInterface) SMPPGatewayClient {
	return &sMPPGatewayClient{cc}
}

func (c *sMPPGatewayClient) DeliverDLR(ctx context.Context, in *DeliverDLRRequest, opts ...grpc.CallOption) (*DeliverDLRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverDLRResponse)
	err := c.cc.Invoke(ctx, SMPPGateway_DeliverDLR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SMPPGatewayServer is the server API for SMPPGateway service.
// All implementations must embed UnimplementedSMPPGatewayServer
// for forward compatibility.
//
// SMPPGateway provides internal gRPC methods for SMPP gateway operations
type SMPPGatewayServer interface {
	// DeliverDLR delivers a DLR (Delivery Receipt) to a connected SMPP client
	DeliverDLR(context.Context, *DeliverDLRRequest) (*DeliverDLRResponse, error)
	mustEmbedUnimplementedSMPPGatewayServer()
}

// UnimplementedSMPPGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSMPPGatewayServer struct{}

func (UnimplementedSMPPGatewayServer) DeliverDLR(context.Context, *DeliverDLRRequest) (*DeliverDLRResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverDLR not implemented")
}
func (UnimplementedSMPPGatewayServer) mustEmbedUnimplementedSMPPGatewayServer() {}
func (UnimplementedSMPPGatewayServer) testEmbeddedByValue()                     {}

// UnsafeSMPPGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SMPPGatewayServer will
// result in compilation errors.
type UnsafeSMPPGatewayServer interface {
	mustEmbedUnimplementedSMPPGatewayServer()
}

func RegisterSMPPGatewayServer(s grpc.ServiceRegistrar, srv SMPPGatewayServer) {
	// If the following call panics, it indicates UnimplementedSMPPGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SMPPGateway_ServiceDesc, srv)
}

func _SMPPGateway_DeliverDLR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverDLRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMPPGatewayServer).DeliverDLR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMPPGateway_DeliverDLR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMPPGatewayServer).DeliverDLR(ctx, req.(*DeliverDLRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SMPPGateway_ServiceDesc is the grpc.ServiceDesc for SMPPGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SMPPGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smpp.v1.SMPPGateway",
	HandlerType: (*SMPPGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverDLR",
			Handler:    _SMPPGateway_DeliverDLR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "smpp.proto",
}
