// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: cascade/cascade.proto

package cascadev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ──────────────────────────────────────────────────────────────────────────
//  CascadeService messages
// ──────────────────────────────────────────────────────────────────────────

type CreateDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	StrategyId    string                 `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Recipient     string                 `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	SenderName    string                 `protobuf:"bytes,5,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,7,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeliveryRequest) Reset()         { *x = CreateDeliveryRequest{} }
func (x *CreateDeliveryRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateDeliveryRequest) ProtoMessage()    {}
func (x *CreateDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*CreateDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDeliveryRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}
func (x *CreateDeliveryRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}
func (x *CreateDeliveryRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}
func (x *CreateDeliveryRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}
func (x *CreateDeliveryRequest) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}
func (x *CreateDeliveryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}
func (x *CreateDeliveryRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────

type DeliveryResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId     string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	StrategyId   string                 `protobuf:"bytes,3,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Recipient    string                 `protobuf:"bytes,4,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Status       string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	DeliveredVia string                 `protobuf:"bytes,6,opt,name=delivered_via,json=deliveredVia,proto3" json:"delivered_via,omitempty"`
	TotalCost    string                 `protobuf:"bytes,7,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Currency     string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	Attempts     []*AttemptInfo         `protobuf:"bytes,9,rep,name=attempts,proto3" json:"attempts,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryResponse) Reset()         { *x = DeliveryResponse{} }
func (x *DeliveryResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DeliveryResponse) ProtoMessage()    {}
func (x *DeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*DeliveryResponse) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *DeliveryResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}
func (x *DeliveryResponse) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}
func (x *DeliveryResponse) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}
func (x *DeliveryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}
func (x *DeliveryResponse) GetDeliveredVia() string {
	if x != nil {
		return x.DeliveredVia
	}
	return ""
}
func (x *DeliveryResponse) GetTotalCost() string {
	if x != nil {
		return x.TotalCost
	}
	return ""
}
func (x *DeliveryResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}
func (x *DeliveryResponse) GetAttempts() []*AttemptInfo {
	if x != nil {
		return x.Attempts
	}
	return nil
}
func (x *DeliveryResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}
func (x *DeliveryResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ──────────────────────────────────────────────────────────────────────────

type AttemptInfo struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelType  string                 `protobuf:"bytes,2,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"`
	StepOrder    int32                  `protobuf:"varint,3,opt,name=step_order,json=stepOrder,proto3" json:"step_order,omitempty"`
	Status       string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Cost         string                 `protobuf:"bytes,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Currency     string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SentAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ResultAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=result_at,json=resultAt,proto3" json:"result_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttemptInfo) Reset()         { *x = AttemptInfo{} }
func (x *AttemptInfo) String() string { return protoimpl.X.MessageStringOf(x) }
func (*AttemptInfo) ProtoMessage()    {}
func (x *AttemptInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*AttemptInfo) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{2}
}

func (x *AttemptInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}
func (x *AttemptInfo) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}
func (x *AttemptInfo) GetStepOrder() int32 {
	if x != nil {
		return x.StepOrder
	}
	return 0
}
func (x *AttemptInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}
func (x *AttemptInfo) GetCost() string {
	if x != nil {
		return x.Cost
	}
	return ""
}
func (x *AttemptInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}
func (x *AttemptInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}
func (x *AttemptInfo) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}
func (x *AttemptInfo) GetResultAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResultAt
	}
	return nil
}

// ──────────────────────────────────────────────────────────────────────────

type GetDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryRequest) Reset()         { *x = GetDeliveryRequest{} }
func (x *GetDeliveryRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetDeliveryRequest) ProtoMessage()    {}
func (x *GetDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeliveryRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}
func (x *GetDeliveryRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────

type ListDeliveriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	StrategyId    string                 `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	DateFrom      string                 `protobuf:"bytes,4,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,5,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveriesRequest) Reset()         { *x = ListDeliveriesRequest{} }
func (x *ListDeliveriesRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListDeliveriesRequest) ProtoMessage()    {}
func (x *ListDeliveriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListDeliveriesRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{4}
}

func (x *ListDeliveriesRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}
func (x *ListDeliveriesRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}
func (x *ListDeliveriesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}
func (x *ListDeliveriesRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}
func (x *ListDeliveriesRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}
func (x *ListDeliveriesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}
func (x *ListDeliveriesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// ──────────────────────────────────────────────────────────────────────────

type ListDeliveriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*DeliveryResponse    `protobuf:"bytes,1,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveriesResponse) Reset()         { *x = ListDeliveriesResponse{} }
func (x *ListDeliveriesResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListDeliveriesResponse) ProtoMessage()    {}
func (x *ListDeliveriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListDeliveriesResponse) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{5}
}

func (x *ListDeliveriesResponse) GetDeliveries() []*DeliveryResponse {
	if x != nil {
		return x.Deliveries
	}
	return nil
}
func (x *ListDeliveriesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}
func (x *ListDeliveriesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

// ──────────────────────────────────────────────────────────────────────────

type GetDeliveryStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	StrategyId    string                 `protobuf:"bytes,2,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	DateFrom      string                 `protobuf:"bytes,3,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,4,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryStatsRequest) Reset()         { *x = GetDeliveryStatsRequest{} }
func (x *GetDeliveryStatsRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetDeliveryStatsRequest) ProtoMessage()    {}
func (x *GetDeliveryStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetDeliveryStatsRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{6}
}

func (x *GetDeliveryStatsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}
func (x *GetDeliveryStatsRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}
func (x *GetDeliveryStatsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}
func (x *GetDeliveryStatsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────

type DeliveryStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalDeliveries int64                  `protobuf:"varint,1,opt,name=total_deliveries,json=totalDeliveries,proto3" json:"total_deliveries,omitempty"`
	DeliveredCount  int64                  `protobuf:"varint,2,opt,name=delivered_count,json=deliveredCount,proto3" json:"delivered_count,omitempty"`
	FailedCount     int64                  `protobuf:"varint,3,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	DeliveryRate    string                 `protobuf:"bytes,4,opt,name=delivery_rate,json=deliveryRate,proto3" json:"delivery_rate,omitempty"`
	ChannelStats    []*ChannelStatItem     `protobuf:"bytes,5,rep,name=channel_stats,json=channelStats,proto3" json:"channel_stats,omitempty"`
	AvgCost         string                 `protobuf:"bytes,6,opt,name=avg_cost,json=avgCost,proto3" json:"avg_cost,omitempty"`
	TotalCost       string                 `protobuf:"bytes,7,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Currency        string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeliveryStatsResponse) Reset()         { *x = DeliveryStatsResponse{} }
func (x *DeliveryStatsResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DeliveryStatsResponse) ProtoMessage()    {}
func (x *DeliveryStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*DeliveryStatsResponse) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{7}
}

func (x *DeliveryStatsResponse) GetTotalDeliveries() int64 {
	if x != nil {
		return x.TotalDeliveries
	}
	return 0
}
func (x *DeliveryStatsResponse) GetDeliveredCount() int64 {
	if x != nil {
		return x.DeliveredCount
	}
	return 0
}
func (x *DeliveryStatsResponse) GetFailedCount() int64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}
func (x *DeliveryStatsResponse) GetDeliveryRate() string {
	if x != nil {
		return x.DeliveryRate
	}
	return ""
}
func (x *DeliveryStatsResponse) GetChannelStats() []*ChannelStatItem {
	if x != nil {
		return x.ChannelStats
	}
	return nil
}
func (x *DeliveryStatsResponse) GetAvgCost() string {
	if x != nil {
		return x.AvgCost
	}
	return ""
}
func (x *DeliveryStatsResponse) GetTotalCost() string {
	if x != nil {
		return x.TotalCost
	}
	return ""
}
func (x *DeliveryStatsResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────

type ChannelStatItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChannelType    string                 `protobuf:"bytes,1,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"`
	AttemptCount   int64                  `protobuf:"varint,2,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	DeliveredCount int64                  `protobuf:"varint,3,opt,name=delivered_count,json=deliveredCount,proto3" json:"delivered_count,omitempty"`
	DeliveryRate   string                 `protobuf:"bytes,4,opt,name=delivery_rate,json=deliveryRate,proto3" json:"delivery_rate,omitempty"`
	AvgLatencyMs   string                 `protobuf:"bytes,5,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	AvgCost        string                 `protobuf:"bytes,6,opt,name=avg_cost,json=avgCost,proto3" json:"avg_cost,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChannelStatItem) Reset()         { *x = ChannelStatItem{} }
func (x *ChannelStatItem) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ChannelStatItem) ProtoMessage()    {}
func (x *ChannelStatItem) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ChannelStatItem) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{8}
}

func (x *ChannelStatItem) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}
func (x *ChannelStatItem) GetAttemptCount() int64 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}
func (x *ChannelStatItem) GetDeliveredCount() int64 {
	if x != nil {
		return x.DeliveredCount
	}
	return 0
}
func (x *ChannelStatItem) GetDeliveryRate() string {
	if x != nil {
		return x.DeliveryRate
	}
	return ""
}
func (x *ChannelStatItem) GetAvgLatencyMs() string {
	if x != nil {
		return x.AvgLatencyMs
	}
	return ""
}
func (x *ChannelStatItem) GetAvgCost() string {
	if x != nil {
		return x.AvgCost
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────
//  ChannelAdminService messages
// ──────────────────────────────────────────────────────────────────────────

type ListChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset()         { *x = ListChannelsRequest{} }
func (x *ListChannelsRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListChannelsRequest) ProtoMessage()    {}
func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{9}
}

// ──────────────────────────────────────────────────────────────────────────

type ListChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*ChannelResponse     `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset()         { *x = ListChannelsResponse{} }
func (x *ListChannelsResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListChannelsResponse) ProtoMessage()    {}
func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{10}
}

func (x *ListChannelsResponse) GetChannels() []*ChannelResponse {
	if x != nil {
		return x.Channels
	}
	return nil
}

// ──────────────────────────────────────────────────────────────────────────

type GetChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelRequest) Reset()         { *x = GetChannelRequest{} }
func (x *GetChannelRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetChannelRequest) ProtoMessage()    {}
func (x *GetChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetChannelRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{11}
}

func (x *GetChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────

type ChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelType   string                 `protobuf:"bytes,2,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelResponse) Reset()         { *x = ChannelResponse{} }
func (x *ChannelResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ChannelResponse) ProtoMessage()    {}
func (x *ChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ChannelResponse) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{12}
}

func (x *ChannelResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}
func (x *ChannelResponse) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}
func (x *ChannelResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *ChannelResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}
func (x *ChannelResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}
func (x *ChannelResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}
func (x *ChannelResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ──────────────────────────────────────────────────────────────────────────

type CreateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelType   string                 `protobuf:"bytes,1,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset()         { *x = CreateChannelRequest{} }
func (x *CreateChannelRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateChannelRequest) ProtoMessage()    {}
func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{13}
}

func (x *CreateChannelRequest) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}
func (x *CreateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *CreateChannelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}
func (x *CreateChannelRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────

type UpdateChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChannelRequest) Reset()         { *x = UpdateChannelRequest{} }
func (x *UpdateChannelRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpdateChannelRequest) ProtoMessage()    {}
func (x *UpdateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*UpdateChannelRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}
func (x *UpdateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *UpdateChannelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}
func (x *UpdateChannelRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────

type ToggleChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleChannelRequest) Reset()         { *x = ToggleChannelRequest{} }
func (x *ToggleChannelRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ToggleChannelRequest) ProtoMessage()    {}
func (x *ToggleChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ToggleChannelRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{15}
}

func (x *ToggleChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}
func (x *ToggleChannelRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// ──────────────────────────────────────────────────────────────────────────
//  StrategyAdminService messages
// ──────────────────────────────────────────────────────────────────────────

type ListStrategiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly    bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStrategiesRequest) Reset()         { *x = ListStrategiesRequest{} }
func (x *ListStrategiesRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListStrategiesRequest) ProtoMessage()    {}
func (x *ListStrategiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListStrategiesRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{16}
}

func (x *ListStrategiesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

// ──────────────────────────────────────────────────────────────────────────

type ListStrategiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategies    []*StrategyResponse    `protobuf:"bytes,1,rep,name=strategies,proto3" json:"strategies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStrategiesResponse) Reset()         { *x = ListStrategiesResponse{} }
func (x *ListStrategiesResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListStrategiesResponse) ProtoMessage()    {}
func (x *ListStrategiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*ListStrategiesResponse) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{17}
}

func (x *ListStrategiesResponse) GetStrategies() []*StrategyResponse {
	if x != nil {
		return x.Strategies
	}
	return nil
}

// ──────────────────────────────────────────────────────────────────────────

type GetStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStrategyRequest) Reset()         { *x = GetStrategyRequest{} }
func (x *GetStrategyRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetStrategyRequest) ProtoMessage()    {}
func (x *GetStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetStrategyRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{18}
}

func (x *GetStrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────

type StrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	Steps         []*StrategyStepInfo    `protobuf:"bytes,6,rep,name=steps,proto3" json:"steps,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyResponse) Reset()         { *x = StrategyResponse{} }
func (x *StrategyResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*StrategyResponse) ProtoMessage()    {}
func (x *StrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*StrategyResponse) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{19}
}

func (x *StrategyResponse) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}
func (x *StrategyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *StrategyResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}
func (x *StrategyResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}
func (x *StrategyResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}
func (x *StrategyResponse) GetSteps() []*StrategyStepInfo {
	if x != nil {
		return x.Steps
	}
	return nil
}
func (x *StrategyResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}
func (x *StrategyResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ──────────────────────────────────────────────────────────────────────────

type StrategyStepInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelType   string                 `protobuf:"bytes,2,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"`
	ChannelName   string                 `protobuf:"bytes,3,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	StepOrder     int32                  `protobuf:"varint,4,opt,name=step_order,json=stepOrder,proto3" json:"step_order,omitempty"`
	TimeoutS      int32                  `protobuf:"varint,5,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`
	Billable      bool                   `protobuf:"varint,6,opt,name=billable,proto3" json:"billable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyStepInfo) Reset()         { *x = StrategyStepInfo{} }
func (x *StrategyStepInfo) String() string { return protoimpl.X.MessageStringOf(x) }
func (*StrategyStepInfo) ProtoMessage()    {}
func (x *StrategyStepInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*StrategyStepInfo) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{20}
}

func (x *StrategyStepInfo) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}
func (x *StrategyStepInfo) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}
func (x *StrategyStepInfo) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}
func (x *StrategyStepInfo) GetStepOrder() int32 {
	if x != nil {
		return x.StepOrder
	}
	return 0
}
func (x *StrategyStepInfo) GetTimeoutS() int32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}
func (x *StrategyStepInfo) GetBillable() bool {
	if x != nil {
		return x.Billable
	}
	return false
}

// ──────────────────────────────────────────────────────────────────────────

type CreateStrategyRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Mode          string                     `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Steps         []*CreateStrategyStepInput `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStrategyRequest) Reset()         { *x = CreateStrategyRequest{} }
func (x *CreateStrategyRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateStrategyRequest) ProtoMessage()    {}
func (x *CreateStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*CreateStrategyRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{21}
}

func (x *CreateStrategyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *CreateStrategyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}
func (x *CreateStrategyRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}
func (x *CreateStrategyRequest) GetSteps() []*CreateStrategyStepInput {
	if x != nil {
		return x.Steps
	}
	return nil
}

// ──────────────────────────────────────────────────────────────────────────

type CreateStrategyStepInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	StepOrder     int32                  `protobuf:"varint,2,opt,name=step_order,json=stepOrder,proto3" json:"step_order,omitempty"`
	TimeoutS      int32                  `protobuf:"varint,3,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`
	Billable      bool                   `protobuf:"varint,4,opt,name=billable,proto3" json:"billable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStrategyStepInput) Reset()         { *x = CreateStrategyStepInput{} }
func (x *CreateStrategyStepInput) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateStrategyStepInput) ProtoMessage()    {}
func (x *CreateStrategyStepInput) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*CreateStrategyStepInput) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{22}
}

func (x *CreateStrategyStepInput) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}
func (x *CreateStrategyStepInput) GetStepOrder() int32 {
	if x != nil {
		return x.StepOrder
	}
	return 0
}
func (x *CreateStrategyStepInput) GetTimeoutS() int32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}
func (x *CreateStrategyStepInput) GetBillable() bool {
	if x != nil {
		return x.Billable
	}
	return false
}

// ──────────────────────────────────────────────────────────────────────────

type UpdateStrategyRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	StrategyId    string                     `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Name          string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Mode          string                     `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Steps         []*CreateStrategyStepInput `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStrategyRequest) Reset()         { *x = UpdateStrategyRequest{} }
func (x *UpdateStrategyRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpdateStrategyRequest) ProtoMessage()    {}
func (x *UpdateStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*UpdateStrategyRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateStrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}
func (x *UpdateStrategyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}
func (x *UpdateStrategyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}
func (x *UpdateStrategyRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}
func (x *UpdateStrategyRequest) GetSteps() []*CreateStrategyStepInput {
	if x != nil {
		return x.Steps
	}
	return nil
}

// ──────────────────────────────────────────────────────────────────────────

type DeleteStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    string                 `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStrategyRequest) Reset()         { *x = DeleteStrategyRequest{} }
func (x *DeleteStrategyRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DeleteStrategyRequest) ProtoMessage()    {}
func (x *DeleteStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*DeleteStrategyRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteStrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────

type DeleteStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStrategyResponse) Reset()         { *x = DeleteStrategyResponse{} }
func (x *DeleteStrategyResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DeleteStrategyResponse) ProtoMessage()    {}
func (x *DeleteStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*DeleteStrategyResponse) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteStrategyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ──────────────────────────────────────────────────────────────────────────

type GetOCSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    string                 `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOCSRequest) Reset()         { *x = GetOCSRequest{} }
func (x *GetOCSRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetOCSRequest) ProtoMessage()    {}
func (x *GetOCSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetOCSRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{26}
}

func (x *GetOCSRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────

type GetOCSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*OCSEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOCSResponse) Reset()         { *x = GetOCSResponse{} }
func (x *GetOCSResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetOCSResponse) ProtoMessage()    {}
func (x *GetOCSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*GetOCSResponse) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{27}
}

func (x *GetOCSResponse) GetEntries() []*OCSEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// ──────────────────────────────────────────────────────────────────────────

type OCSEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    string                 `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	OperatorName  string                 `protobuf:"bytes,2,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	ChannelType   string                 `protobuf:"bytes,3,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"`
	Supported     bool                   `protobuf:"varint,4,opt,name=supported,proto3" json:"supported,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OCSEntry) Reset()         { *x = OCSEntry{} }
func (x *OCSEntry) String() string { return protoimpl.X.MessageStringOf(x) }
func (*OCSEntry) ProtoMessage()    {}
func (x *OCSEntry) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*OCSEntry) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{28}
}

func (x *OCSEntry) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}
func (x *OCSEntry) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}
func (x *OCSEntry) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}
func (x *OCSEntry) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}
func (x *OCSEntry) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────

type UpdateOCSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    string                 `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	ChannelType   string                 `protobuf:"bytes,2,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"`
	Supported     bool                   `protobuf:"varint,3,opt,name=supported,proto3" json:"supported,omitempty"`
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOCSRequest) Reset()         { *x = UpdateOCSRequest{} }
func (x *UpdateOCSRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpdateOCSRequest) ProtoMessage()    {}
func (x *UpdateOCSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*UpdateOCSRequest) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateOCSRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}
func (x *UpdateOCSRequest) GetChannelType() string {
	if x != nil {
		return x.ChannelType
	}
	return ""
}
func (x *UpdateOCSRequest) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}
func (x *UpdateOCSRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────

type UpdateOCSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *OCSEntry              `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOCSResponse) Reset()         { *x = UpdateOCSResponse{} }
func (x *UpdateOCSResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*UpdateOCSResponse) ProtoMessage()    {}
func (x *UpdateOCSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cascade_cascade_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*UpdateOCSResponse) Descriptor() ([]byte, []int) {
	return file_cascade_cascade_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateOCSResponse) GetEntry() *OCSEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// ──────────────────────────────────────────────────────────────────────────
//  File descriptor stubs
// ──────────────────────────────────────────────────────────────────────────

var file_cascade_cascade_proto_rawDescOnce sync.Once
var file_cascade_cascade_proto_rawDescData []byte

func file_cascade_cascade_proto_rawDescGZIP() []byte {
	file_cascade_cascade_proto_rawDescOnce.Do(func() {
		file_cascade_cascade_proto_rawDescData = protoimpl.X.CompressGZIP(file_cascade_cascade_proto_rawDescData)
	})
	return file_cascade_cascade_proto_rawDescData
}

var file_cascade_cascade_proto_msgTypes = make([]protoimpl.MessageInfo, 31)

// Ensure unused imports are referenced.
var (
	_ = reflect.TypeOf
	_ = sync.Once{}
	_ = unsafe.Sizeof(0)
	_ = timestamppb.Timestamp{}
)
