// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: analytics/analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetStatisticsRequest представляет запрос на получение статистики
type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`          // ID клиента (опционально, для фильтрации)
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`                                  // Начало периода
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`                                      // Конец периода
	GroupBy       string                 `protobuf:"bytes,4,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`             // Группировка (day, hour, provider, status)
	ProviderIds   []string               `protobuf:"bytes,5,rep,name=provider_ids,json=providerIds,proto3" json:"provider_ids,omitempty"` // Фильтр по провайдерам (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatisticsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetStatisticsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetStatisticsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetStatisticsRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

func (x *GetStatisticsRequest) GetProviderIds() []string {
	if x != nil {
		return x.ProviderIds
	}
	return nil
}

// GetStatisticsResponse представляет ответ со статистикой
type GetStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*StatisticGroup      `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"` // Группы статистики
	Totals        *TotalStats            `protobuf:"bytes,2,opt,name=totals,proto3" json:"totals,omitempty"` // Общая статистика
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	mi := &file_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatisticsResponse) GetGroups() []*StatisticGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetStatisticsResponse) GetTotals() *TotalStats {
	if x != nil {
		return x.Totals
	}
	return nil
}

// GenerateReportRequest представляет запрос на генерацию отчета
type GenerateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportType    string                 `protobuf:"bytes,1,opt,name=report_type,json=reportType,proto3" json:"report_type,omitempty"` // Тип отчета (daily, monthly, provider, client)
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`                               // Начало периода
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`                                   // Конец периода
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`       // ID клиента (опционально)
	ProviderId    string                 `protobuf:"bytes,5,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // ID провайдера (опционально)
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`                           // Формат отчета (json, csv, pdf)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportRequest) Reset() {
	*x = GenerateReportRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportRequest) ProtoMessage() {}

func (x *GenerateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateReportRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateReportRequest) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *GenerateReportRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GenerateReportRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GenerateReportRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GenerateReportRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *GenerateReportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// GenerateReportResponse представляет ответ с отчетом
type GenerateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`          // ID отчета
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`                              // Формат отчета
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                  // Данные отчета
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"` // Время генерации
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportResponse) Reset() {
	*x = GenerateReportResponse{}
	mi := &file_analytics_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportResponse) ProtoMessage() {}

func (x *GenerateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportResponse.ProtoReflect.Descriptor instead.
func (*GenerateReportResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateReportResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *GenerateReportResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GenerateReportResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GenerateReportResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

// GetRealtimeMetricsRequest представляет запрос на получение метрик в реальном времени
type GetRealtimeMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealtimeMetricsRequest) Reset() {
	*x = GetRealtimeMetricsRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealtimeMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealtimeMetricsRequest) ProtoMessage() {}

func (x *GetRealtimeMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealtimeMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetRealtimeMetricsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{4}
}

// GetRealtimeMetricsResponse представляет ответ с метриками в реальном времени
type GetRealtimeMetricsResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MessagesPerSecond       int64                  `protobuf:"varint,1,opt,name=messages_per_second,json=messagesPerSecond,proto3" json:"messages_per_second,omitempty"`                                                                   // Сообщений в секунду
	TotalMessagesQueued     int64                  `protobuf:"varint,2,opt,name=total_messages_queued,json=totalMessagesQueued,proto3" json:"total_messages_queued,omitempty"`                                                             // Всего сообщений в очереди
	TotalMessagesProcessing int64                  `protobuf:"varint,3,opt,name=total_messages_processing,json=totalMessagesProcessing,proto3" json:"total_messages_processing,omitempty"`                                                 // Всего сообщений в обработке
	ActiveProviders         int64                  `protobuf:"varint,4,opt,name=active_providers,json=activeProviders,proto3" json:"active_providers,omitempty"`                                                                           // Количество активных провайдеров
	ActiveConnections       int64                  `protobuf:"varint,5,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`                                                                     // Количество активных соединений
	ProviderMetrics         map[string]int64       `protobuf:"bytes,6,rep,name=provider_metrics,json=providerMetrics,proto3" json:"provider_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Метрики по провайдерам
	Timestamp               *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                                                               // Время сбора метрик
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetRealtimeMetricsResponse) Reset() {
	*x = GetRealtimeMetricsResponse{}
	mi := &file_analytics_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealtimeMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealtimeMetricsResponse) ProtoMessage() {}

func (x *GetRealtimeMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealtimeMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetRealtimeMetricsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetRealtimeMetricsResponse) GetMessagesPerSecond() int64 {
	if x != nil {
		return x.MessagesPerSecond
	}
	return 0
}

func (x *GetRealtimeMetricsResponse) GetTotalMessagesQueued() int64 {
	if x != nil {
		return x.TotalMessagesQueued
	}
	return 0
}

func (x *GetRealtimeMetricsResponse) GetTotalMessagesProcessing() int64 {
	if x != nil {
		return x.TotalMessagesProcessing
	}
	return 0
}

func (x *GetRealtimeMetricsResponse) GetActiveProviders() int64 {
	if x != nil {
		return x.ActiveProviders
	}
	return 0
}

func (x *GetRealtimeMetricsResponse) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *GetRealtimeMetricsResponse) GetProviderMetrics() map[string]int64 {
	if x != nil {
		return x.ProviderMetrics
	}
	return nil
}

func (x *GetRealtimeMetricsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// GetProviderPerformanceRequest представляет запрос на получение производительности провайдера
type GetProviderPerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // ID провайдера
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`                               // Начало периода
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`                                   // Конец периода
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderPerformanceRequest) Reset() {
	*x = GetProviderPerformanceRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderPerformanceRequest) ProtoMessage() {}

func (x *GetProviderPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderPerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetProviderPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetProviderPerformanceRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *GetProviderPerformanceRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetProviderPerformanceRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

// GetProviderPerformanceResponse представляет ответ с производительностью провайдера
type GetProviderPerformanceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProviderId        string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`                                                                                           // ID провайдера
	TotalSent         int64                  `protobuf:"varint,2,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`                                                                                             // Всего отправлено
	TotalDelivered    int64                  `protobuf:"varint,3,opt,name=total_delivered,json=totalDelivered,proto3" json:"total_delivered,omitempty"`                                                                              // Всего доставлено
	TotalFailed       int64                  `protobuf:"varint,4,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`                                                                                       // Всего неудачных
	SuccessRate       int32                  `protobuf:"varint,5,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`                                                                                       // Процент успешных (0-100)
	AvgDeliveryTimeMs int64                  `protobuf:"varint,6,opt,name=avg_delivery_time_ms,json=avgDeliveryTimeMs,proto3" json:"avg_delivery_time_ms,omitempty"`                                                                 // Среднее время доставки в миллисекундах
	StatusBreakdown   map[string]int64       `protobuf:"bytes,7,rep,name=status_breakdown,json=statusBreakdown,proto3" json:"status_breakdown,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Разбивка по статусам
	Points            []*PerformancePoint    `protobuf:"bytes,8,rep,name=points,proto3" json:"points,omitempty"`                                                                                                                     // Точки производительности (для графиков)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetProviderPerformanceResponse) Reset() {
	*x = GetProviderPerformanceResponse{}
	mi := &file_analytics_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderPerformanceResponse) ProtoMessage() {}

func (x *GetProviderPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderPerformanceResponse.ProtoReflect.Descriptor instead.
func (*GetProviderPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetProviderPerformanceResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *GetProviderPerformanceResponse) GetTotalSent() int64 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *GetProviderPerformanceResponse) GetTotalDelivered() int64 {
	if x != nil {
		return x.TotalDelivered
	}
	return 0
}

func (x *GetProviderPerformanceResponse) GetTotalFailed() int64 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *GetProviderPerformanceResponse) GetSuccessRate() int32 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *GetProviderPerformanceResponse) GetAvgDeliveryTimeMs() int64 {
	if x != nil {
		return x.AvgDeliveryTimeMs
	}
	return 0
}

func (x *GetProviderPerformanceResponse) GetStatusBreakdown() map[string]int64 {
	if x != nil {
		return x.StatusBreakdown
	}
	return nil
}

func (x *GetProviderPerformanceResponse) GetPoints() []*PerformancePoint {
	if x != nil {
		return x.Points
	}
	return nil
}

// StatisticGroup представляет группу статистики
type StatisticGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // Ключ группы (дата, провайдер, статус)
	Stats         *TotalStats            `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"` // Статистика для этой группы
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatisticGroup) Reset() {
	*x = StatisticGroup{}
	mi := &file_analytics_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatisticGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticGroup) ProtoMessage() {}

func (x *StatisticGroup) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticGroup.ProtoReflect.Descriptor instead.
func (*StatisticGroup) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *StatisticGroup) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StatisticGroup) GetStats() *TotalStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// TotalStats представляет общую статистику
type TotalStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalSent         int64                  `protobuf:"varint,1,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`                             // Всего отправлено
	TotalDelivered    int64                  `protobuf:"varint,2,opt,name=total_delivered,json=totalDelivered,proto3" json:"total_delivered,omitempty"`              // Всего доставлено
	TotalFailed       int64                  `protobuf:"varint,3,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`                       // Всего неудачных
	TotalPending      int64                  `protobuf:"varint,4,opt,name=total_pending,json=totalPending,proto3" json:"total_pending,omitempty"`                    // Всего в ожидании
	TotalQueued       int64                  `protobuf:"varint,5,opt,name=total_queued,json=totalQueued,proto3" json:"total_queued,omitempty"`                       // Всего в очереди
	SuccessRate       int32                  `protobuf:"varint,6,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`                       // Процент успешных (0-100)
	AvgDeliveryTimeMs int64                  `protobuf:"varint,7,opt,name=avg_delivery_time_ms,json=avgDeliveryTimeMs,proto3" json:"avg_delivery_time_ms,omitempty"` // Среднее время доставки в миллисекундах
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TotalStats) Reset() {
	*x = TotalStats{}
	mi := &file_analytics_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalStats) ProtoMessage() {}

func (x *TotalStats) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalStats.ProtoReflect.Descriptor instead.
func (*TotalStats) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *TotalStats) GetTotalSent() int64 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *TotalStats) GetTotalDelivered() int64 {
	if x != nil {
		return x.TotalDelivered
	}
	return 0
}

func (x *TotalStats) GetTotalFailed() int64 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *TotalStats) GetTotalPending() int64 {
	if x != nil {
		return x.TotalPending
	}
	return 0
}

func (x *TotalStats) GetTotalQueued() int64 {
	if x != nil {
		return x.TotalQueued
	}
	return 0
}

func (x *TotalStats) GetSuccessRate() int32 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *TotalStats) GetAvgDeliveryTimeMs() int64 {
	if x != nil {
		return x.AvgDeliveryTimeMs
	}
	return 0
}

// PerformancePoint представляет точку производительности
type PerformancePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                         // Время точки
	Sent          int64                  `protobuf:"varint,2,opt,name=sent,proto3" json:"sent,omitempty"`                                  // Отправлено
	Delivered     int64                  `protobuf:"varint,3,opt,name=delivered,proto3" json:"delivered,omitempty"`                        // Доставлено
	Failed        int64                  `protobuf:"varint,4,opt,name=failed,proto3" json:"failed,omitempty"`                              // Неудачных
	SuccessRate   int32                  `protobuf:"varint,5,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"` // Процент успешных
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformancePoint) Reset() {
	*x = PerformancePoint{}
	mi := &file_analytics_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformancePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformancePoint) ProtoMessage() {}

func (x *PerformancePoint) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformancePoint.ProtoReflect.Descriptor instead.
func (*PerformancePoint) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *PerformancePoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PerformancePoint) GetSent() int64 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *PerformancePoint) GetDelivered() int64 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

func (x *PerformancePoint) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *PerformancePoint) GetSuccessRate() int32 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

var File_analytics_analytics_proto protoreflect.FileDescriptor

const file_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"\x19analytics/analytics.proto\x12\fanalytics.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x01\n" +
	"\x14GetStatisticsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x19\n" +
	"\bgroup_by\x18\x04 \x01(\tR\agroupBy\x12!\n" +
	"\fprovider_ids\x18\x05 \x03(\tR\vproviderIds\"\x7f\n" +
	"\x15GetStatisticsResponse\x124\n" +
	"\x06groups\x18\x01 \x03(\v2\x1c.analytics.v1.StatisticGroupR\x06groups\x120\n" +
	"\x06totals\x18\x02 \x01(\v2\x18.analytics.v1.TotalStatsR\x06totals\"\xea\x01\n" +
	"\x15GenerateReportRequest\x12\x1f\n" +
	"\vreport_type\x18\x01 \x01(\tR\n" +
	"reportType\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x1f\n" +
	"\vprovider_id\x18\x05 \x01(\tR\n" +
	"providerId\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\"\xa0\x01\n" +
	"\x16GenerateReportResponse\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12=\n" +
	"\fgenerated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"\x1b\n" +
	"\x19GetRealtimeMetricsRequest\"\xfe\x03\n" +
	"\x1aGetRealtimeMetricsResponse\x12.\n" +
	"\x13messages_per_second\x18\x01 \x01(\x03R\x11messagesPerSecond\x122\n" +
	"\x15total_messages_queued\x18\x02 \x01(\x03R\x13totalMessagesQueued\x12:\n" +
	"\x19total_messages_processing\x18\x03 \x01(\x03R\x17totalMessagesProcessing\x12)\n" +
	"\x10active_providers\x18\x04 \x01(\x03R\x0factiveProviders\x12-\n" +
	"\x12active_connections\x18\x05 \x01(\x03R\x11activeConnections\x12h\n" +
	"\x10provider_metrics\x18\x06 \x03(\v2=.analytics.v1.GetRealtimeMetricsResponse.ProviderMetricsEntryR\x0fproviderMetrics\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1aB\n" +
	"\x14ProviderMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x9c\x01\n" +
	"\x1dGetProviderPerformanceRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"\xea\x03\n" +
	"\x1eGetProviderPerformanceResponse\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1d\n" +
	"\n" +
	"total_sent\x18\x02 \x01(\x03R\ttotalSent\x12'\n" +
	"\x0ftotal_delivered\x18\x03 \x01(\x03R\x0etotalDelivered\x12!\n" +
	"\ftotal_failed\x18\x04 \x01(\x03R\vtotalFailed\x12!\n" +
	"\fsuccess_rate\x18\x05 \x01(\x05R\vsuccessRate\x12/\n" +
	"\x14avg_delivery_time_ms\x18\x06 \x01(\x03R\x11avgDeliveryTimeMs\x12l\n" +
	"\x10status_breakdown\x18\a \x03(\v2A.analytics.v1.GetProviderPerformanceResponse.StatusBreakdownEntryR\x0fstatusBreakdown\x126\n" +
	"\x06points\x18\b \x03(\v2\x1e.analytics.v1.PerformancePointR\x06points\x1aB\n" +
	"\x14StatusBreakdownEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"R\n" +
	"\x0eStatisticGroup\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05stats\x18\x02 \x01(\v2\x18.analytics.v1.TotalStatsR\x05stats\"\x93\x02\n" +
	"\n" +
	"TotalStats\x12\x1d\n" +
	"\n" +
	"total_sent\x18\x01 \x01(\x03R\ttotalSent\x12'\n" +
	"\x0ftotal_delivered\x18\x02 \x01(\x03R\x0etotalDelivered\x12!\n" +
	"\ftotal_failed\x18\x03 \x01(\x03R\vtotalFailed\x12#\n" +
	"\rtotal_pending\x18\x04 \x01(\x03R\ftotalPending\x12!\n" +
	"\ftotal_queued\x18\x05 \x01(\x03R\vtotalQueued\x12!\n" +
	"\fsuccess_rate\x18\x06 \x01(\x05R\vsuccessRate\x12/\n" +
	"\x14avg_delivery_time_ms\x18\a \x01(\x03R\x11avgDeliveryTimeMs\"\xb9\x01\n" +
	"\x10PerformancePoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04sent\x18\x02 \x01(\x03R\x04sent\x12\x1c\n" +
	"\tdelivered\x18\x03 \x01(\x03R\tdelivered\x12\x16\n" +
	"\x06failed\x18\x04 \x01(\x03R\x06failed\x12!\n" +
	"\fsuccess_rate\x18\x05 \x01(\x05R\vsuccessRate2\xa7\x03\n" +
	"\x10AnalyticsService\x12X\n" +
	"\rGetStatistics\x12\".analytics.v1.GetStatisticsRequest\x1a#.analytics.v1.GetStatisticsResponse\x12[\n" +
	"\x0eGenerateReport\x12#.analytics.v1.GenerateReportRequest\x1a$.analytics.v1.GenerateReportResponse\x12g\n" +
	"\x12GetRealtimeMetrics\x12'.analytics.v1.GetRealtimeMetricsRequest\x1a(.analytics.v1.GetRealtimeMetricsResponse\x12s\n" +
	"\x16GetProviderPerformance\x12+.analytics.v1.GetProviderPerformanceRequest\x1a,.analytics.v1.GetProviderPerformanceResponseB:Z8github.com/smpp-server/smpp-server/api/proto/analyticsv1b\x06proto3"

var (
	file_analytics_analytics_proto_rawDescOnce sync.Once
	file_analytics_analytics_proto_rawDescData []byte
)

func file_analytics_analytics_proto_rawDescGZIP() []byte {
	file_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_analytics_proto_rawDesc), len(file_analytics_analytics_proto_rawDesc)))
	})
	return file_analytics_analytics_proto_rawDescData
}

var file_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_analytics_analytics_proto_goTypes = []any{
	(*GetStatisticsRequest)(nil),           // 0: analytics.v1.GetStatisticsRequest
	(*GetStatisticsResponse)(nil),          // 1: analytics.v1.GetStatisticsResponse
	(*GenerateReportRequest)(nil),          // 2: analytics.v1.GenerateReportRequest
	(*GenerateReportResponse)(nil),         // 3: analytics.v1.GenerateReportResponse
	(*GetRealtimeMetricsRequest)(nil),      // 4: analytics.v1.GetRealtimeMetricsRequest
	(*GetRealtimeMetricsResponse)(nil),     // 5: analytics.v1.GetRealtimeMetricsResponse
	(*GetProviderPerformanceRequest)(nil),  // 6: analytics.v1.GetProviderPerformanceRequest
	(*GetProviderPerformanceResponse)(nil), // 7: analytics.v1.GetProviderPerformanceResponse
	(*StatisticGroup)(nil),                 // 8: analytics.v1.StatisticGroup
	(*TotalStats)(nil),                     // 9: analytics.v1.TotalStats
	(*PerformancePoint)(nil),               // 10: analytics.v1.PerformancePoint
	nil,                                    // 11: analytics.v1.GetRealtimeMetricsResponse.ProviderMetricsEntry
	nil,                                    // 12: analytics.v1.GetProviderPerformanceResponse.StatusBreakdownEntry
	(*timestamppb.Timestamp)(nil),          // 13: google.protobuf.Timestamp
}
var file_analytics_analytics_proto_depIdxs = []int32{
	13, // 0: analytics.v1.GetStatisticsRequest.from:type_name -> google.protobuf.Timestamp
	13, // 1: analytics.v1.GetStatisticsRequest.to:type_name -> google.protobuf.Timestamp
	8,  // 2: analytics.v1.GetStatisticsResponse.groups:type_name -> analytics.v1.StatisticGroup
	9,  // 3: analytics.v1.GetStatisticsResponse.totals:type_name -> analytics.v1.TotalStats
	13, // 4: analytics.v1.GenerateReportRequest.from:type_name -> google.protobuf.Timestamp
	13, // 5: analytics.v1.GenerateReportRequest.to:type_name -> google.protobuf.Timestamp
	13, // 6: analytics.v1.GenerateReportResponse.generated_at:type_name -> google.protobuf.Timestamp
	11, // 7: analytics.v1.GetRealtimeMetricsResponse.provider_metrics:type_name -> analytics.v1.GetRealtimeMetricsResponse.ProviderMetricsEntry
	13, // 8: analytics.v1.GetRealtimeMetricsResponse.timestamp:type_name -> google.protobuf.Timestamp
	13, // 9: analytics.v1.GetProviderPerformanceRequest.from:type_name -> google.protobuf.Timestamp
	13, // 10: analytics.v1.GetProviderPerformanceRequest.to:type_name -> google.protobuf.Timestamp
	12, // 11: analytics.v1.GetProviderPerformanceResponse.status_breakdown:type_name -> analytics.v1.GetProviderPerformanceResponse.StatusBreakdownEntry
	10, // 12: analytics.v1.GetProviderPerformanceResponse.points:type_name -> analytics.v1.PerformancePoint
	9,  // 13: analytics.v1.StatisticGroup.stats:type_name -> analytics.v1.TotalStats
	13, // 14: analytics.v1.PerformancePoint.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 15: analytics.v1.AnalyticsService.GetStatistics:input_type -> analytics.v1.GetStatisticsRequest
	2,  // 16: analytics.v1.AnalyticsService.GenerateReport:input_type -> analytics.v1.GenerateReportRequest
	4,  // 17: analytics.v1.AnalyticsService.GetRealtimeMetrics:input_type -> analytics.v1.GetRealtimeMetricsRequest
	6,  // 18: analytics.v1.AnalyticsService.GetProviderPerformance:input_type -> analytics.v1.GetProviderPerformanceRequest
	1,  // 19: analytics.v1.AnalyticsService.GetStatistics:output_type -> analytics.v1.GetStatisticsResponse
	3,  // 20: analytics.v1.AnalyticsService.GenerateReport:output_type -> analytics.v1.GenerateReportResponse
	5,  // 21: analytics.v1.AnalyticsService.GetRealtimeMetrics:output_type -> analytics.v1.GetRealtimeMetricsResponse
	7,  // 22: analytics.v1.AnalyticsService.GetProviderPerformance:output_type -> analytics.v1.GetProviderPerformanceResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_analytics_analytics_proto_init() }
func file_analytics_analytics_proto_init() {
	if File_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_analytics_proto_rawDesc), len(file_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_analytics_proto_msgTypes,
	}.Build()
	File_analytics_analytics_proto = out.File
	file_analytics_analytics_proto_goTypes = nil
	file_analytics_analytics_proto_depIdxs = nil
}
