ALTER TABLE providers
  ADD COLUMN IF NOT EXISTS client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS tps_limit INTEGER NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS routing_rules JSONB NOT NULL DEFAULT '[]';

CREATE INDEX IF NOT EXISTS idx_providers_client_id ON providers(client_id);
