ALTER TABLE accounts ADD COLUMN IF NOT EXISTS frozen BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS credit_limit DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS low_balance_threshold DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS frozen_at TIMESTAMPTZ;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS frozen_by UUID REFERENCES users(id);
