ALTER TABLE templates ADD COLUMN IF NOT EXISTS reviewer_id UUID REFERENCES users(id);
ALTER TABLE templates ADD COLUMN IF NOT EXISTS review_comment TEXT;
ALTER TABLE templates ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;
