// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: provider/provider.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateProviderRequest представляет запрос на создание провайдера
type CreateProviderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                    // Название провайдера
	Host           string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`                                                                                    // Хост SMSC
	Port           int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                                                                                   // Порт SMSC
	SystemId       string                 `protobuf:"bytes,4,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`                                                            // System ID для bind
	Password       string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`                                                                            // Пароль для bind
	SystemType     string                 `protobuf:"bytes,6,opt,name=system_type,json=systemType,proto3" json:"system_type,omitempty"`                                                      // System Type (опционально)
	AddrTon        int32                  `protobuf:"varint,7,opt,name=addr_ton,json=addrTon,proto3" json:"addr_ton,omitempty"`                                                              // Address TON (опционально)
	AddrNpi        int32                  `protobuf:"varint,8,opt,name=addr_npi,json=addrNpi,proto3" json:"addr_npi,omitempty"`                                                              // Address NPI (опционально)
	BindType       int32                  `protobuf:"varint,9,opt,name=bind_type,json=bindType,proto3" json:"bind_type,omitempty"`                                                           // Тип bind (1=TX, 2=RX, 3=TRX)
	MaxConnections int32                  `protobuf:"varint,10,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`                                        // Максимальное количество соединений
	WindowSize     int32                  `protobuf:"varint,11,opt,name=window_size,json=windowSize,proto3" json:"window_size,omitempty"`                                                    // Размер окна (опционально)
	Active         bool                   `protobuf:"varint,12,opt,name=active,proto3" json:"active,omitempty"`                                                                              // Активен ли провайдер
	Settings       map[string]string      `protobuf:"bytes,13,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Дополнительные настройки
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateProviderRequest) Reset() {
	*x = CreateProviderRequest{}
	mi := &file_provider_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderRequest) ProtoMessage() {}

func (x *CreateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateProviderRequest) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProviderRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *CreateProviderRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CreateProviderRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *CreateProviderRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateProviderRequest) GetSystemType() string {
	if x != nil {
		return x.SystemType
	}
	return ""
}

func (x *CreateProviderRequest) GetAddrTon() int32 {
	if x != nil {
		return x.AddrTon
	}
	return 0
}

func (x *CreateProviderRequest) GetAddrNpi() int32 {
	if x != nil {
		return x.AddrNpi
	}
	return 0
}

func (x *CreateProviderRequest) GetBindType() int32 {
	if x != nil {
		return x.BindType
	}
	return 0
}

func (x *CreateProviderRequest) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *CreateProviderRequest) GetWindowSize() int32 {
	if x != nil {
		return x.WindowSize
	}
	return 0
}

func (x *CreateProviderRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *CreateProviderRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

// CreateProviderResponse представляет ответ на создание провайдера
type CreateProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // ID созданного провайдера
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // Время создания
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderResponse) Reset() {
	*x = CreateProviderResponse{}
	mi := &file_provider_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderResponse) ProtoMessage() {}

func (x *CreateProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderResponse.ProtoReflect.Descriptor instead.
func (*CreateProviderResponse) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProviderResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *CreateProviderResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// UpdateProviderRequest представляет запрос на обновление провайдера
type UpdateProviderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProviderId     string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`                                                     // ID провайдера
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // Название провайдера (опционально)
	Host           string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`                                                                                   // Хост SMSC (опционально)
	Port           int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`                                                                                  // Порт SMSC (опционально)
	SystemId       string                 `protobuf:"bytes,5,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`                                                           // System ID (опционально)
	Password       string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`                                                                           // Пароль (опционально)
	MaxConnections int32                  `protobuf:"varint,7,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`                                        // Максимальное количество соединений (опционально)
	Active         bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`                                                                              // Активен ли провайдер (опционально)
	Settings       map[string]string      `protobuf:"bytes,9,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Дополнительные настройки (опционально)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProviderRequest) Reset() {
	*x = UpdateProviderRequest{}
	mi := &file_provider_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderRequest) ProtoMessage() {}

func (x *UpdateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateProviderRequest) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProviderRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *UpdateProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProviderRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *UpdateProviderRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *UpdateProviderRequest) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *UpdateProviderRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateProviderRequest) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *UpdateProviderRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *UpdateProviderRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

// UpdateProviderResponse представляет ответ на обновление провайдера
type UpdateProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Успешность операции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderResponse) Reset() {
	*x = UpdateProviderResponse{}
	mi := &file_provider_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderResponse) ProtoMessage() {}

func (x *UpdateProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderResponse.ProtoReflect.Descriptor instead.
func (*UpdateProviderResponse) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetProviderRequest представляет запрос на получение провайдера
type GetProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // ID провайдера
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRequest) Reset() {
	*x = GetProviderRequest{}
	mi := &file_provider_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRequest) ProtoMessage() {}

func (x *GetProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRequest.ProtoReflect.Descriptor instead.
func (*GetProviderRequest) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{4}
}

func (x *GetProviderRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

// GetProviderResponse представляет ответ с информацией о провайдере
type GetProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderInfo          `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // Информация о провайдере
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderResponse) Reset() {
	*x = GetProviderResponse{}
	mi := &file_provider_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderResponse) ProtoMessage() {}

func (x *GetProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderResponse.ProtoReflect.Descriptor instead.
func (*GetProviderResponse) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{5}
}

func (x *GetProviderResponse) GetProvider() *ProviderInfo {
	if x != nil {
		return x.Provider
	}
	return nil
}

// ListProvidersRequest представляет запрос на получение списка провайдеров
type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly    bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"` // Только активные провайдеры
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                             // Лимит записей
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                           // Смещение для пагинации
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_provider_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{6}
}

func (x *ListProvidersRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *ListProvidersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProvidersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListProvidersResponse представляет ответ со списком провайдеров
type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderInfo        `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"` // Список провайдеров
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`        // Общее количество
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_provider_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{7}
}

func (x *ListProvidersResponse) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *ListProvidersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// DeleteProviderRequest представляет запрос на удаление провайдера
type DeleteProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // ID провайдера
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderRequest) Reset() {
	*x = DeleteProviderRequest{}
	mi := &file_provider_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderRequest) ProtoMessage() {}

func (x *DeleteProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderRequest.ProtoReflect.Descriptor instead.
func (*DeleteProviderRequest) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProviderRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

// GetProviderHealthRequest представляет запрос на получение статуса здоровья
type GetProviderHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"` // ID провайдера
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderHealthRequest) Reset() {
	*x = GetProviderHealthRequest{}
	mi := &file_provider_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderHealthRequest) ProtoMessage() {}

func (x *GetProviderHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderHealthRequest.ProtoReflect.Descriptor instead.
func (*GetProviderHealthRequest) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{9}
}

func (x *GetProviderHealthRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

// GetProviderHealthResponse представляет ответ со статусом здоровья
type GetProviderHealthResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProviderId         string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`                         // ID провайдера
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                                   // Статус (healthy, unhealthy, degraded)
	ActiveConnections  int32                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`   // Количество активных соединений
	TotalConnections   int32                  `protobuf:"varint,4,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`      // Общее количество соединений
	SuccessRate        int32                  `protobuf:"varint,5,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`                     // Процент успешных отправок (0-100)
	MessagesSent_24H   int64                  `protobuf:"varint,6,opt,name=messages_sent_24h,json=messagesSent24h,proto3" json:"messages_sent_24h,omitempty"`       // Количество отправленных сообщений за 24 часа
	MessagesFailed_24H int64                  `protobuf:"varint,7,opt,name=messages_failed_24h,json=messagesFailed24h,proto3" json:"messages_failed_24h,omitempty"` // Количество неудачных сообщений за 24 часа
	LastSuccess        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_success,json=lastSuccess,proto3" json:"last_success,omitempty"`                      // Время последней успешной отправки
	LastFailure        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_failure,json=lastFailure,proto3" json:"last_failure,omitempty"`                      // Время последней неудачи
	LastError          string                 `protobuf:"bytes,10,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`                           // Последняя ошибка (опционально)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetProviderHealthResponse) Reset() {
	*x = GetProviderHealthResponse{}
	mi := &file_provider_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderHealthResponse) ProtoMessage() {}

func (x *GetProviderHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderHealthResponse.ProtoReflect.Descriptor instead.
func (*GetProviderHealthResponse) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{10}
}

func (x *GetProviderHealthResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *GetProviderHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetProviderHealthResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *GetProviderHealthResponse) GetTotalConnections() int32 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *GetProviderHealthResponse) GetSuccessRate() int32 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *GetProviderHealthResponse) GetMessagesSent_24H() int64 {
	if x != nil {
		return x.MessagesSent_24H
	}
	return 0
}

func (x *GetProviderHealthResponse) GetMessagesFailed_24H() int64 {
	if x != nil {
		return x.MessagesFailed_24H
	}
	return 0
}

func (x *GetProviderHealthResponse) GetLastSuccess() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccess
	}
	return nil
}

func (x *GetProviderHealthResponse) GetLastFailure() *timestamppb.Timestamp {
	if x != nil {
		return x.LastFailure
	}
	return nil
}

func (x *GetProviderHealthResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// SendToProviderRequest представляет запрос на отправку через провайдера
type SendToProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`                                                                           // ID провайдера
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`                                                                              // ID сообщения
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`                                                                                                     // Отправитель
	Destination   string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`                                                                                           // Получатель
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`                                                                                                         // Текст сообщения
	SmppParams    map[string]string      `protobuf:"bytes,6,rep,name=smpp_params,json=smppParams,proto3" json:"smpp_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Дополнительные SMPP параметры
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToProviderRequest) Reset() {
	*x = SendToProviderRequest{}
	mi := &file_provider_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToProviderRequest) ProtoMessage() {}

func (x *SendToProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToProviderRequest.ProtoReflect.Descriptor instead.
func (*SendToProviderRequest) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{11}
}

func (x *SendToProviderRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *SendToProviderRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendToProviderRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SendToProviderRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SendToProviderRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendToProviderRequest) GetSmppParams() map[string]string {
	if x != nil {
		return x.SmppParams
	}
	return nil
}

// SendToProviderResponse представляет ответ на отправку
type SendToProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                   // Успешность отправки
	SmppMessageId string                 `protobuf:"bytes,2,opt,name=smpp_message_id,json=smppMessageId,proto3" json:"smpp_message_id,omitempty"` // SMPP message ID (если успешно)
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                                        // Ошибка (если неуспешно)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToProviderResponse) Reset() {
	*x = SendToProviderResponse{}
	mi := &file_provider_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToProviderResponse) ProtoMessage() {}

func (x *SendToProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToProviderResponse.ProtoReflect.Descriptor instead.
func (*SendToProviderResponse) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{12}
}

func (x *SendToProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendToProviderResponse) GetSmppMessageId() string {
	if x != nil {
		return x.SmppMessageId
	}
	return ""
}

func (x *SendToProviderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ProviderInfo представляет информацию о провайдере
type ProviderInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProviderId     string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`                                                      // ID провайдера
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                    // Название провайдера
	Host           string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`                                                                                    // Хост SMSC
	Port           int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`                                                                                   // Порт SMSC
	SystemId       string                 `protobuf:"bytes,5,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`                                                            // System ID
	SystemType     string                 `protobuf:"bytes,6,opt,name=system_type,json=systemType,proto3" json:"system_type,omitempty"`                                                      // System Type
	BindType       int32                  `protobuf:"varint,7,opt,name=bind_type,json=bindType,proto3" json:"bind_type,omitempty"`                                                           // Тип bind
	MaxConnections int32                  `protobuf:"varint,8,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`                                         // Максимальное количество соединений
	WindowSize     int32                  `protobuf:"varint,9,opt,name=window_size,json=windowSize,proto3" json:"window_size,omitempty"`                                                     // Размер окна
	Active         bool                   `protobuf:"varint,10,opt,name=active,proto3" json:"active,omitempty"`                                                                              // Активен ли провайдер
	Settings       map[string]string      `protobuf:"bytes,11,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Дополнительные настройки
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                        // Время создания
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                        // Время обновления
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_provider_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_provider_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_provider_provider_proto_rawDescGZIP(), []int{13}
}

func (x *ProviderInfo) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProviderInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProviderInfo) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *ProviderInfo) GetSystemType() string {
	if x != nil {
		return x.SystemType
	}
	return ""
}

func (x *ProviderInfo) GetBindType() int32 {
	if x != nil {
		return x.BindType
	}
	return 0
}

func (x *ProviderInfo) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *ProviderInfo) GetWindowSize() int32 {
	if x != nil {
		return x.WindowSize
	}
	return 0
}

func (x *ProviderInfo) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ProviderInfo) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ProviderInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProviderInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_provider_provider_proto protoreflect.FileDescriptor

const file_provider_provider_proto_rawDesc = "" +
	"\n" +
	"\x17provider/provider.proto\x12\vprovider.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x03\n" +
	"\x15CreateProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1b\n" +
	"\tsystem_id\x18\x04 \x01(\tR\bsystemId\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1f\n" +
	"\vsystem_type\x18\x06 \x01(\tR\n" +
	"systemType\x12\x19\n" +
	"\baddr_ton\x18\a \x01(\x05R\aaddrTon\x12\x19\n" +
	"\baddr_npi\x18\b \x01(\x05R\aaddrNpi\x12\x1b\n" +
	"\tbind_type\x18\t \x01(\x05R\bbindType\x12'\n" +
	"\x0fmax_connections\x18\n" +
	" \x01(\x05R\x0emaxConnections\x12\x1f\n" +
	"\vwindow_size\x18\v \x01(\x05R\n" +
	"windowSize\x12\x16\n" +
	"\x06active\x18\f \x01(\bR\x06active\x12L\n" +
	"\bsettings\x18\r \x03(\v20.provider.v1.CreateProviderRequest.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x16CreateProviderResponse\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf9\x02\n" +
	"\x15UpdateProviderRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1b\n" +
	"\tsystem_id\x18\x05 \x01(\tR\bsystemId\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12'\n" +
	"\x0fmax_connections\x18\a \x01(\x05R\x0emaxConnections\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\x12L\n" +
	"\bsettings\x18\t \x03(\v20.provider.v1.UpdateProviderRequest.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x16UpdateProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x12GetProviderRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"L\n" +
	"\x13GetProviderResponse\x125\n" +
	"\bprovider\x18\x01 \x01(\v2\x19.provider.v1.ProviderInfoR\bprovider\"e\n" +
	"\x14ListProvidersRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"f\n" +
	"\x15ListProvidersResponse\x127\n" +
	"\tproviders\x18\x01 \x03(\v2\x19.provider.v1.ProviderInfoR\tproviders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"8\n" +
	"\x15DeleteProviderRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\";\n" +
	"\x18GetProviderHealthRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"\xcc\x03\n" +
	"\x19GetProviderHealthResponse\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x05R\x11activeConnections\x12+\n" +
	"\x11total_connections\x18\x04 \x01(\x05R\x10totalConnections\x12!\n" +
	"\fsuccess_rate\x18\x05 \x01(\x05R\vsuccessRate\x12*\n" +
	"\x11messages_sent_24h\x18\x06 \x01(\x03R\x0fmessagesSent24h\x12.\n" +
	"\x13messages_failed_24h\x18\a \x01(\x03R\x11messagesFailed24h\x12=\n" +
	"\flast_success\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vlastSuccess\x12=\n" +
	"\flast_failure\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vlastFailure\x12\x1d\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\tR\tlastError\"\xb9\x02\n" +
	"\x15SendToProviderRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12S\n" +
	"\vsmpp_params\x18\x06 \x03(\v22.provider.v1.SendToProviderRequest.SmppParamsEntryR\n" +
	"smppParams\x1a=\n" +
	"\x0fSmppParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x16SendToProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fsmpp_message_id\x18\x02 \x01(\tR\rsmppMessageId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa0\x04\n" +
	"\fProviderInfo\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1b\n" +
	"\tsystem_id\x18\x05 \x01(\tR\bsystemId\x12\x1f\n" +
	"\vsystem_type\x18\x06 \x01(\tR\n" +
	"systemType\x12\x1b\n" +
	"\tbind_type\x18\a \x01(\x05R\bbindType\x12'\n" +
	"\x0fmax_connections\x18\b \x01(\x05R\x0emaxConnections\x12\x1f\n" +
	"\vwindow_size\x18\t \x01(\x05R\n" +
	"windowSize\x12\x16\n" +
	"\x06active\x18\n" +
	" \x01(\bR\x06active\x12C\n" +
	"\bsettings\x18\v \x03(\v2'.provider.v1.ProviderInfo.SettingsEntryR\bsettings\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8a\x05\n" +
	"\x0fProviderService\x12Y\n" +
	"\x0eCreateProvider\x12\".provider.v1.CreateProviderRequest\x1a#.provider.v1.CreateProviderResponse\x12Y\n" +
	"\x0eUpdateProvider\x12\".provider.v1.UpdateProviderRequest\x1a#.provider.v1.UpdateProviderResponse\x12P\n" +
	"\vGetProvider\x12\x1f.provider.v1.GetProviderRequest\x1a .provider.v1.GetProviderResponse\x12V\n" +
	"\rListProviders\x12!.provider.v1.ListProvidersRequest\x1a\".provider.v1.ListProvidersResponse\x12X\n" +
	"\x0eDeleteProvider\x12\".provider.v1.DeleteProviderRequest\x1a\".provider.v1.DeleteProviderRequest\x12b\n" +
	"\x11GetProviderHealth\x12%.provider.v1.GetProviderHealthRequest\x1a&.provider.v1.GetProviderHealthResponse\x12Y\n" +
	"\x0eSendToProvider\x12\".provider.v1.SendToProviderRequest\x1a#.provider.v1.SendToProviderResponseB9Z7github.com/smpp-server/smpp-server/api/proto/providerv1b\x06proto3"

var (
	file_provider_provider_proto_rawDescOnce sync.Once
	file_provider_provider_proto_rawDescData []byte
)

func file_provider_provider_proto_rawDescGZIP() []byte {
	file_provider_provider_proto_rawDescOnce.Do(func() {
		file_provider_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_provider_proto_rawDesc), len(file_provider_provider_proto_rawDesc)))
	})
	return file_provider_provider_proto_rawDescData
}

var file_provider_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_provider_provider_proto_goTypes = []any{
	(*CreateProviderRequest)(nil),     // 0: provider.v1.CreateProviderRequest
	(*CreateProviderResponse)(nil),    // 1: provider.v1.CreateProviderResponse
	(*UpdateProviderRequest)(nil),     // 2: provider.v1.UpdateProviderRequest
	(*UpdateProviderResponse)(nil),    // 3: provider.v1.UpdateProviderResponse
	(*GetProviderRequest)(nil),        // 4: provider.v1.GetProviderRequest
	(*GetProviderResponse)(nil),       // 5: provider.v1.GetProviderResponse
	(*ListProvidersRequest)(nil),      // 6: provider.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),     // 7: provider.v1.ListProvidersResponse
	(*DeleteProviderRequest)(nil),     // 8: provider.v1.DeleteProviderRequest
	(*GetProviderHealthRequest)(nil),  // 9: provider.v1.GetProviderHealthRequest
	(*GetProviderHealthResponse)(nil), // 10: provider.v1.GetProviderHealthResponse
	(*SendToProviderRequest)(nil),     // 11: provider.v1.SendToProviderRequest
	(*SendToProviderResponse)(nil),    // 12: provider.v1.SendToProviderResponse
	(*ProviderInfo)(nil),              // 13: provider.v1.ProviderInfo
	nil,                               // 14: provider.v1.CreateProviderRequest.SettingsEntry
	nil,                               // 15: provider.v1.UpdateProviderRequest.SettingsEntry
	nil,                               // 16: provider.v1.SendToProviderRequest.SmppParamsEntry
	nil,                               // 17: provider.v1.ProviderInfo.SettingsEntry
	(*timestamppb.Timestamp)(nil),     // 18: google.protobuf.Timestamp
}
var file_provider_provider_proto_depIdxs = []int32{
	14, // 0: provider.v1.CreateProviderRequest.settings:type_name -> provider.v1.CreateProviderRequest.SettingsEntry
	18, // 1: provider.v1.CreateProviderResponse.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: provider.v1.UpdateProviderRequest.settings:type_name -> provider.v1.UpdateProviderRequest.SettingsEntry
	13, // 3: provider.v1.GetProviderResponse.provider:type_name -> provider.v1.ProviderInfo
	13, // 4: provider.v1.ListProvidersResponse.providers:type_name -> provider.v1.ProviderInfo
	18, // 5: provider.v1.GetProviderHealthResponse.last_success:type_name -> google.protobuf.Timestamp
	18, // 6: provider.v1.GetProviderHealthResponse.last_failure:type_name -> google.protobuf.Timestamp
	16, // 7: provider.v1.SendToProviderRequest.smpp_params:type_name -> provider.v1.SendToProviderRequest.SmppParamsEntry
	17, // 8: provider.v1.ProviderInfo.settings:type_name -> provider.v1.ProviderInfo.SettingsEntry
	18, // 9: provider.v1.ProviderInfo.created_at:type_name -> google.protobuf.Timestamp
	18, // 10: provider.v1.ProviderInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 11: provider.v1.ProviderService.CreateProvider:input_type -> provider.v1.CreateProviderRequest
	2,  // 12: provider.v1.ProviderService.UpdateProvider:input_type -> provider.v1.UpdateProviderRequest
	4,  // 13: provider.v1.ProviderService.GetProvider:input_type -> provider.v1.GetProviderRequest
	6,  // 14: provider.v1.ProviderService.ListProviders:input_type -> provider.v1.ListProvidersRequest
	8,  // 15: provider.v1.ProviderService.DeleteProvider:input_type -> provider.v1.DeleteProviderRequest
	9,  // 16: provider.v1.ProviderService.GetProviderHealth:input_type -> provider.v1.GetProviderHealthRequest
	11, // 17: provider.v1.ProviderService.SendToProvider:input_type -> provider.v1.SendToProviderRequest
	1,  // 18: provider.v1.ProviderService.CreateProvider:output_type -> provider.v1.CreateProviderResponse
	3,  // 19: provider.v1.ProviderService.UpdateProvider:output_type -> provider.v1.UpdateProviderResponse
	5,  // 20: provider.v1.ProviderService.GetProvider:output_type -> provider.v1.GetProviderResponse
	7,  // 21: provider.v1.ProviderService.ListProviders:output_type -> provider.v1.ListProvidersResponse
	8,  // 22: provider.v1.ProviderService.DeleteProvider:output_type -> provider.v1.DeleteProviderRequest
	10, // 23: provider.v1.ProviderService.GetProviderHealth:output_type -> provider.v1.GetProviderHealthResponse
	12, // 24: provider.v1.ProviderService.SendToProvider:output_type -> provider.v1.SendToProviderResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_provider_provider_proto_init() }
func file_provider_provider_proto_init() {
	if File_provider_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_provider_proto_rawDesc), len(file_provider_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_provider_proto_goTypes,
		DependencyIndexes: file_provider_provider_proto_depIdxs,
		MessageInfos:      file_provider_provider_proto_msgTypes,
	}.Build()
	File_provider_provider_proto = out.File
	file_provider_provider_proto_goTypes = nil
	file_provider_provider_proto_depIdxs = nil
}
