; deployments/configs/pgbouncer.ini
[databases]
smpp_db = host=postgres port=5432 dbname=smpp_db

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 6432
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt

pool_mode = transaction
max_client_conn = 200
default_pool_size = 30
reserve_pool_size = 5
reserve_pool_timeout = 3
server_idle_timeout = 300

log_connections = 0
log_disconnections = 0
log_pooler_errors = 1

admin_users = smpp
stats_users = smpp
