// api/proto/sender-name/sender_name.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: sender-name/sender_name.proto

package sendernamev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SenderNameService_CreateSenderName_FullMethodName     = "/sendername.v1.SenderNameService/CreateSenderName"
	SenderNameService_UpdateSenderName_FullMethodName     = "/sendername.v1.SenderNameService/UpdateSenderName"
	SenderNameService_GetSenderName_FullMethodName        = "/sendername.v1.SenderNameService/GetSenderName"
	SenderNameService_ListSenderNames_FullMethodName      = "/sendername.v1.SenderNameService/ListSenderNames"
	SenderNameService_ResubmitSenderName_FullMethodName   = "/sendername.v1.SenderNameService/ResubmitSenderName"
	SenderNameService_GetSenderNameHistory_FullMethodName = "/sendername.v1.SenderNameService/GetSenderNameHistory"
	SenderNameService_ApproveSenderName_FullMethodName    = "/sendername.v1.SenderNameService/ApproveSenderName"
	SenderNameService_RejectSenderName_FullMethodName     = "/sendername.v1.SenderNameService/RejectSenderName"
	SenderNameService_DeactivateSenderName_FullMethodName = "/sendername.v1.SenderNameService/DeactivateSenderName"
	SenderNameService_ListAllSenderNames_FullMethodName   = "/sendername.v1.SenderNameService/ListAllSenderNames"
)

// SenderNameServiceClient is the client API for SenderNameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SenderNameService управляет именами отправителей SMS.
// Размещается в template-service (порт 9099).
type SenderNameServiceClient interface {
	// Создать заявку на регистрацию имени отправителя.
	// Новая заявка получает статус "pending".
	CreateSenderName(ctx context.Context, in *CreateSenderNameRequest, opts ...grpc.CallOption) (*CreateSenderNameResponse, error)
	// Обновить имя отправителя. Разрешено только в статусе "rejected".
	// После обновления статус НЕ меняется автоматически — нужен ResubmitSenderName.
	UpdateSenderName(ctx context.Context, in *UpdateSenderNameRequest, opts ...grpc.CallOption) (*UpdateSenderNameResponse, error)
	// Получить имя отправителя по ID.
	GetSenderName(ctx context.Context, in *GetSenderNameRequest, opts ...grpc.CallOption) (*GetSenderNameResponse, error)
	// Получить список имён отправителей клиента.
	ListSenderNames(ctx context.Context, in *ListSenderNamesRequest, opts ...grpc.CallOption) (*ListSenderNamesResponse, error)
	// Повторно отправить отклонённую заявку на рассмотрение.
	// Статус меняется rejected → pending.
	ResubmitSenderName(ctx context.Context, in *ResubmitSenderNameRequest, opts ...grpc.CallOption) (*ResubmitSenderNameResponse, error)
	// Получить историю изменений статуса.
	GetSenderNameHistory(ctx context.Context, in *GetSenderNameHistoryRequest, opts ...grpc.CallOption) (*GetSenderNameHistoryResponse, error)
	// Одобрить заявку. Статус pending → approved.
	ApproveSenderName(ctx context.Context, in *ApproveSenderNameRequest, opts ...grpc.CallOption) (*ApproveSenderNameResponse, error)
	// Отклонить заявку с указанием причины. Статус pending → rejected.
	RejectSenderName(ctx context.Context, in *RejectSenderNameRequest, opts ...grpc.CallOption) (*RejectSenderNameResponse, error)
	// Деактивировать одобренное имя. Статус approved → deactivated.
	DeactivateSenderName(ctx context.Context, in *DeactivateSenderNameRequest, opts ...grpc.CallOption) (*DeactivateSenderNameResponse, error)
	// Список всех заявок (для admin panel), с фильтрацией по статусу.
	ListAllSenderNames(ctx context.Context, in *ListAllSenderNamesRequest, opts ...grpc.CallOption) (*ListAllSenderNamesResponse, error)
}

type senderNameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSenderNameServiceClient(cc grpc.ClientConnInterface) SenderNameServiceClient {
	return &senderNameServiceClient{cc}
}

func (c *senderNameServiceClient) CreateSenderName(ctx context.Context, in *CreateSenderNameRequest, opts ...grpc.CallOption) (*CreateSenderNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSenderNameResponse)
	err := c.cc.Invoke(ctx, SenderNameService_CreateSenderName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senderNameServiceClient) UpdateSenderName(ctx context.Context, in *UpdateSenderNameRequest, opts ...grpc.CallOption) (*UpdateSenderNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSenderNameResponse)
	err := c.cc.Invoke(ctx, SenderNameService_UpdateSenderName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senderNameServiceClient) GetSenderName(ctx context.Context, in *GetSenderNameRequest, opts ...grpc.CallOption) (*GetSenderNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSenderNameResponse)
	err := c.cc.Invoke(ctx, SenderNameService_GetSenderName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senderNameServiceClient) ListSenderNames(ctx context.Context, in *ListSenderNamesRequest, opts ...grpc.CallOption) (*ListSenderNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSenderNamesResponse)
	err := c.cc.Invoke(ctx, SenderNameService_ListSenderNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senderNameServiceClient) ResubmitSenderName(ctx context.Context, in *ResubmitSenderNameRequest, opts ...grpc.CallOption) (*ResubmitSenderNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResubmitSenderNameResponse)
	err := c.cc.Invoke(ctx, SenderNameService_ResubmitSenderName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senderNameServiceClient) GetSenderNameHistory(ctx context.Context, in *GetSenderNameHistoryRequest, opts ...grpc.CallOption) (*GetSenderNameHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSenderNameHistoryResponse)
	err := c.cc.Invoke(ctx, SenderNameService_GetSenderNameHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senderNameServiceClient) ApproveSenderName(ctx context.Context, in *ApproveSenderNameRequest, opts ...grpc.CallOption) (*ApproveSenderNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveSenderNameResponse)
	err := c.cc.Invoke(ctx, SenderNameService_ApproveSenderName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senderNameServiceClient) RejectSenderName(ctx context.Context, in *RejectSenderNameRequest, opts ...grpc.CallOption) (*RejectSenderNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectSenderNameResponse)
	err := c.cc.Invoke(ctx, SenderNameService_RejectSenderName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senderNameServiceClient) DeactivateSenderName(ctx context.Context, in *DeactivateSenderNameRequest, opts ...grpc.CallOption) (*DeactivateSenderNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateSenderNameResponse)
	err := c.cc.Invoke(ctx, SenderNameService_DeactivateSenderName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *senderNameServiceClient) ListAllSenderNames(ctx context.Context, in *ListAllSenderNamesRequest, opts ...grpc.CallOption) (*ListAllSenderNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllSenderNamesResponse)
	err := c.cc.Invoke(ctx, SenderNameService_ListAllSenderNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SenderNameServiceServer is the server API for SenderNameService service.
// All implementations must embed UnimplementedSenderNameServiceServer
// for forward compatibility.
//
// SenderNameService управляет именами отправителей SMS.
// Размещается в template-service (порт 9099).
type SenderNameServiceServer interface {
	// Создать заявку на регистрацию имени отправителя.
	// Новая заявка получает статус "pending".
	CreateSenderName(context.Context, *CreateSenderNameRequest) (*CreateSenderNameResponse, error)
	// Обновить имя отправителя. Разрешено только в статусе "rejected".
	// После обновления статус НЕ меняется автоматически — нужен ResubmitSenderName.
	UpdateSenderName(context.Context, *UpdateSenderNameRequest) (*UpdateSenderNameResponse, error)
	// Получить имя отправителя по ID.
	GetSenderName(context.Context, *GetSenderNameRequest) (*GetSenderNameResponse, error)
	// Получить список имён отправителей клиента.
	ListSenderNames(context.Context, *ListSenderNamesRequest) (*ListSenderNamesResponse, error)
	// Повторно отправить отклонённую заявку на рассмотрение.
	// Статус меняется rejected → pending.
	ResubmitSenderName(context.Context, *ResubmitSenderNameRequest) (*ResubmitSenderNameResponse, error)
	// Получить историю изменений статуса.
	GetSenderNameHistory(context.Context, *GetSenderNameHistoryRequest) (*GetSenderNameHistoryResponse, error)
	// Одобрить заявку. Статус pending → approved.
	ApproveSenderName(context.Context, *ApproveSenderNameRequest) (*ApproveSenderNameResponse, error)
	// Отклонить заявку с указанием причины. Статус pending → rejected.
	RejectSenderName(context.Context, *RejectSenderNameRequest) (*RejectSenderNameResponse, error)
	// Деактивировать одобренное имя. Статус approved → deactivated.
	DeactivateSenderName(context.Context, *DeactivateSenderNameRequest) (*DeactivateSenderNameResponse, error)
	// Список всех заявок (для admin panel), с фильтрацией по статусу.
	ListAllSenderNames(context.Context, *ListAllSenderNamesRequest) (*ListAllSenderNamesResponse, error)
	mustEmbedUnimplementedSenderNameServiceServer()
}

// UnimplementedSenderNameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSenderNameServiceServer struct{}

func (UnimplementedSenderNameServiceServer) CreateSenderName(context.Context, *CreateSenderNameRequest) (*CreateSenderNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSenderName not implemented")
}
func (UnimplementedSenderNameServiceServer) UpdateSenderName(context.Context, *UpdateSenderNameRequest) (*UpdateSenderNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSenderName not implemented")
}
func (UnimplementedSenderNameServiceServer) GetSenderName(context.Context, *GetSenderNameRequest) (*GetSenderNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSenderName not implemented")
}
func (UnimplementedSenderNameServiceServer) ListSenderNames(context.Context, *ListSenderNamesRequest) (*ListSenderNamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSenderNames not implemented")
}
func (UnimplementedSenderNameServiceServer) ResubmitSenderName(context.Context, *ResubmitSenderNameRequest) (*ResubmitSenderNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResubmitSenderName not implemented")
}
func (UnimplementedSenderNameServiceServer) GetSenderNameHistory(context.Context, *GetSenderNameHistoryRequest) (*GetSenderNameHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSenderNameHistory not implemented")
}
func (UnimplementedSenderNameServiceServer) ApproveSenderName(context.Context, *ApproveSenderNameRequest) (*ApproveSenderNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveSenderName not implemented")
}
func (UnimplementedSenderNameServiceServer) RejectSenderName(context.Context, *RejectSenderNameRequest) (*RejectSenderNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectSenderName not implemented")
}
func (UnimplementedSenderNameServiceServer) DeactivateSenderName(context.Context, *DeactivateSenderNameRequest) (*DeactivateSenderNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateSenderName not implemented")
}
func (UnimplementedSenderNameServiceServer) ListAllSenderNames(context.Context, *ListAllSenderNamesRequest) (*ListAllSenderNamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllSenderNames not implemented")
}
func (UnimplementedSenderNameServiceServer) mustEmbedUnimplementedSenderNameServiceServer() {}
func (UnimplementedSenderNameServiceServer) testEmbeddedByValue()                           {}

// UnsafeSenderNameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SenderNameServiceServer will
// result in compilation errors.
type UnsafeSenderNameServiceServer interface {
	mustEmbedUnimplementedSenderNameServiceServer()
}

func RegisterSenderNameServiceServer(s grpc.ServiceRegistrar, srv SenderNameServiceServer) {
	// If the following call panics, it indicates UnimplementedSenderNameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SenderNameService_ServiceDesc, srv)
}

func _SenderNameService_CreateSenderName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSenderNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderNameServiceServer).CreateSenderName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SenderNameService_CreateSenderName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderNameServiceServer).CreateSenderName(ctx, req.(*CreateSenderNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SenderNameService_UpdateSenderName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSenderNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderNameServiceServer).UpdateSenderName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SenderNameService_UpdateSenderName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderNameServiceServer).UpdateSenderName(ctx, req.(*UpdateSenderNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SenderNameService_GetSenderName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSenderNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderNameServiceServer).GetSenderName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SenderNameService_GetSenderName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderNameServiceServer).GetSenderName(ctx, req.(*GetSenderNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SenderNameService_ListSenderNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSenderNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderNameServiceServer).ListSenderNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SenderNameService_ListSenderNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderNameServiceServer).ListSenderNames(ctx, req.(*ListSenderNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SenderNameService_ResubmitSenderName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResubmitSenderNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderNameServiceServer).ResubmitSenderName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SenderNameService_ResubmitSenderName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderNameServiceServer).ResubmitSenderName(ctx, req.(*ResubmitSenderNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SenderNameService_GetSenderNameHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSenderNameHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderNameServiceServer).GetSenderNameHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SenderNameService_GetSenderNameHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderNameServiceServer).GetSenderNameHistory(ctx, req.(*GetSenderNameHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SenderNameService_ApproveSenderName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveSenderNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderNameServiceServer).ApproveSenderName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SenderNameService_ApproveSenderName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderNameServiceServer).ApproveSenderName(ctx, req.(*ApproveSenderNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SenderNameService_RejectSenderName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectSenderNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderNameServiceServer).RejectSenderName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SenderNameService_RejectSenderName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderNameServiceServer).RejectSenderName(ctx, req.(*RejectSenderNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SenderNameService_DeactivateSenderName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateSenderNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderNameServiceServer).DeactivateSenderName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SenderNameService_DeactivateSenderName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderNameServiceServer).DeactivateSenderName(ctx, req.(*DeactivateSenderNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SenderNameService_ListAllSenderNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllSenderNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SenderNameServiceServer).ListAllSenderNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SenderNameService_ListAllSenderNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SenderNameServiceServer).ListAllSenderNames(ctx, req.(*ListAllSenderNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SenderNameService_ServiceDesc is the grpc.ServiceDesc for SenderNameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SenderNameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sendername.v1.SenderNameService",
	HandlerType: (*SenderNameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSenderName",
			Handler:    _SenderNameService_CreateSenderName_Handler,
		},
		{
			MethodName: "UpdateSenderName",
			Handler:    _SenderNameService_UpdateSenderName_Handler,
		},
		{
			MethodName: "GetSenderName",
			Handler:    _SenderNameService_GetSenderName_Handler,
		},
		{
			MethodName: "ListSenderNames",
			Handler:    _SenderNameService_ListSenderNames_Handler,
		},
		{
			MethodName: "ResubmitSenderName",
			Handler:    _SenderNameService_ResubmitSenderName_Handler,
		},
		{
			MethodName: "GetSenderNameHistory",
			Handler:    _SenderNameService_GetSenderNameHistory_Handler,
		},
		{
			MethodName: "ApproveSenderName",
			Handler:    _SenderNameService_ApproveSenderName_Handler,
		},
		{
			MethodName: "RejectSenderName",
			Handler:    _SenderNameService_RejectSenderName_Handler,
		},
		{
			MethodName: "DeactivateSenderName",
			Handler:    _SenderNameService_DeactivateSenderName_Handler,
		},
		{
			MethodName: "ListAllSenderNames",
			Handler:    _SenderNameService_ListAllSenderNames_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sender-name/sender_name.proto",
}
