// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: client/client.proto

package clientv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateClientRequest представляет запрос на создание клиента
type CreateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // Название клиента
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                                                                                 // Email клиента
	ContactPerson string                 `protobuf:"bytes,3,opt,name=contact_person,json=contactPerson,proto3" json:"contact_person,omitempty"`                                            // Контактное лицо (опционально)
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`                                                                                 // Телефон (опционально)
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`                                                                              // Активен ли клиент
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Дополнительные метаданные
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_client_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{0}
}

func (x *CreateClientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClientRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateClientRequest) GetContactPerson() string {
	if x != nil {
		return x.ContactPerson
	}
	return ""
}

func (x *CreateClientRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateClientRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *CreateClientRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// CreateClientResponse представляет ответ на создание клиента
type CreateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`    // ID созданного клиента
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Время создания
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientResponse) Reset() {
	*x = CreateClientResponse{}
	mi := &file_client_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientResponse) ProtoMessage() {}

func (x *CreateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientResponse.ProtoReflect.Descriptor instead.
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{1}
}

func (x *CreateClientResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateClientResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// UpdateClientRequest представляет запрос на обновление клиента
type UpdateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                                                           // ID клиента
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // Название клиента (опционально)
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                                                                                 // Email клиента (опционально)
	ContactPerson string                 `protobuf:"bytes,4,opt,name=contact_person,json=contactPerson,proto3" json:"contact_person,omitempty"`                                            // Контактное лицо (опционально)
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`                                                                                 // Телефон (опционально)
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`                                                                              // Активен ли клиент (опционально)
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Дополнительные метаданные (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientRequest) Reset() {
	*x = UpdateClientRequest{}
	mi := &file_client_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientRequest) ProtoMessage() {}

func (x *UpdateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UpdateClientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateClientRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateClientRequest) GetContactPerson() string {
	if x != nil {
		return x.ContactPerson
	}
	return ""
}

func (x *UpdateClientRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateClientRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *UpdateClientRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// UpdateClientResponse представляет ответ на обновление клиента
type UpdateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Успешность операции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientResponse) Reset() {
	*x = UpdateClientResponse{}
	mi := &file_client_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientResponse) ProtoMessage() {}

func (x *UpdateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientResponse.ProtoReflect.Descriptor instead.
func (*UpdateClientResponse) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetClientRequest представляет запрос на получение клиента
type GetClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // ID клиента
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientRequest) Reset() {
	*x = GetClientRequest{}
	mi := &file_client_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRequest) ProtoMessage() {}

func (x *GetClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientRequest.ProtoReflect.Descriptor instead.
func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{4}
}

func (x *GetClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// GetClientResponse представляет ответ с информацией о клиенте
type GetClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *ClientInfo            `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"` // Информация о клиенте
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientResponse) Reset() {
	*x = GetClientResponse{}
	mi := &file_client_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientResponse) ProtoMessage() {}

func (x *GetClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientResponse.ProtoReflect.Descriptor instead.
func (*GetClientResponse) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{5}
}

func (x *GetClientResponse) GetClient() *ClientInfo {
	if x != nil {
		return x.Client
	}
	return nil
}

// ListClientsRequest представляет запрос на получение списка клиентов
type ListClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveOnly    bool                   `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"` // Только активные клиенты
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`                            // Поисковый запрос (опционально)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                             // Лимит записей
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`                           // Смещение для пагинации
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
	mi := &file_client_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsRequest.ProtoReflect.Descriptor instead.
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{6}
}

func (x *ListClientsRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *ListClientsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListClientsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListClientsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ListClientsResponse представляет ответ со списком клиентов
type ListClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*ClientInfo          `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"` // Список клиентов
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`    // Общее количество
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_client_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{7}
}

func (x *ListClientsResponse) GetClients() []*ClientInfo {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ListClientsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// DeleteClientRequest представляет запрос на удаление клиента
type DeleteClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // ID клиента
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientRequest) Reset() {
	*x = DeleteClientRequest{}
	mi := &file_client_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientRequest) ProtoMessage() {}

func (x *DeleteClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientRequest.ProtoReflect.Descriptor instead.
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// DeleteClientResponse представляет ответ на удаление клиента
type DeleteClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Успешность операции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClientResponse) Reset() {
	*x = DeleteClientResponse{}
	mi := &file_client_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClientResponse) ProtoMessage() {}

func (x *DeleteClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClientResponse.ProtoReflect.Descriptor instead.
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetClientConfigRequest представляет запрос на получение конфигурации
type GetClientConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // ID клиента
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientConfigRequest) Reset() {
	*x = GetClientConfigRequest{}
	mi := &file_client_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientConfigRequest) ProtoMessage() {}

func (x *GetClientConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientConfigRequest.ProtoReflect.Descriptor instead.
func (*GetClientConfigRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{10}
}

func (x *GetClientConfigRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// GetClientConfigResponse представляет ответ с конфигурацией
type GetClientConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ClientConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"` // Конфигурация клиента
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientConfigResponse) Reset() {
	*x = GetClientConfigResponse{}
	mi := &file_client_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientConfigResponse) ProtoMessage() {}

func (x *GetClientConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientConfigResponse.ProtoReflect.Descriptor instead.
func (*GetClientConfigResponse) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{11}
}

func (x *GetClientConfigResponse) GetConfig() *ClientConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// UpdateClientConfigRequest представляет запрос на обновление конфигурации
type UpdateClientConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // ID клиента
	Config        *ClientConfig          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`                     // Новая конфигурация
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientConfigRequest) Reset() {
	*x = UpdateClientConfigRequest{}
	mi := &file_client_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientConfigRequest) ProtoMessage() {}

func (x *UpdateClientConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientConfigRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateClientConfigRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UpdateClientConfigRequest) GetConfig() *ClientConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// UpdateClientConfigResponse представляет ответ на обновление конфигурации
type UpdateClientConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Успешность операции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientConfigResponse) Reset() {
	*x = UpdateClientConfigResponse{}
	mi := &file_client_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientConfigResponse) ProtoMessage() {}

func (x *UpdateClientConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateClientConfigResponse) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateClientConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// UpdateClientRateLimitsRequest представляет запрос на обновление rate limits
type UpdateClientRateLimitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`       // ID клиента
	RateLimits    *RateLimits            `protobuf:"bytes,2,opt,name=rate_limits,json=rateLimits,proto3" json:"rate_limits,omitempty"` // Новые rate limits
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientRateLimitsRequest) Reset() {
	*x = UpdateClientRateLimitsRequest{}
	mi := &file_client_client_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientRateLimitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientRateLimitsRequest) ProtoMessage() {}

func (x *UpdateClientRateLimitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientRateLimitsRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientRateLimitsRequest) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateClientRateLimitsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UpdateClientRateLimitsRequest) GetRateLimits() *RateLimits {
	if x != nil {
		return x.RateLimits
	}
	return nil
}

// UpdateClientRateLimitsResponse представляет ответ на обновление rate limits
type UpdateClientRateLimitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Успешность операции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientRateLimitsResponse) Reset() {
	*x = UpdateClientRateLimitsResponse{}
	mi := &file_client_client_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientRateLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientRateLimitsResponse) ProtoMessage() {}

func (x *UpdateClientRateLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientRateLimitsResponse.ProtoReflect.Descriptor instead.
func (*UpdateClientRateLimitsResponse) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateClientRateLimitsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ClientInfo представляет информацию о клиенте
type ClientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                                                           // ID клиента
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                   // Название клиента
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                                                                                 // Email клиента
	ContactPerson string                 `protobuf:"bytes,4,opt,name=contact_person,json=contactPerson,proto3" json:"contact_person,omitempty"`                                            // Контактное лицо
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`                                                                                 // Телефон
	Active        bool                   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`                                                                              // Активен ли клиент
	RateLimits    *RateLimits            `protobuf:"bytes,7,opt,name=rate_limits,json=rateLimits,proto3" json:"rate_limits,omitempty"`                                                     // Rate limits
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Дополнительные метаданные
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                        // Время создания
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                       // Время обновления
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_client_client_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{16}
}

func (x *ClientInfo) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ClientInfo) GetContactPerson() string {
	if x != nil {
		return x.ContactPerson
	}
	return ""
}

func (x *ClientInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ClientInfo) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ClientInfo) GetRateLimits() *RateLimits {
	if x != nil {
		return x.RateLimits
	}
	return nil
}

func (x *ClientInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClientInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ClientInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ClientConfig представляет конфигурацию клиента
type ClientConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ClientId            string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`                                                           // ID клиента
	RateLimits          *RateLimits            `protobuf:"bytes,2,opt,name=rate_limits,json=rateLimits,proto3" json:"rate_limits,omitempty"`                                                     // Rate limits
	AllowedSources      []string               `protobuf:"bytes,3,rep,name=allowed_sources,json=allowedSources,proto3" json:"allowed_sources,omitempty"`                                         // Разрешенные номера отправителей
	BlockedDestinations []string               `protobuf:"bytes,4,rep,name=blocked_destinations,json=blockedDestinations,proto3" json:"blocked_destinations,omitempty"`                          // Заблокированные номера получателей
	Settings            map[string]string      `protobuf:"bytes,5,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Дополнительные настройки
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                        // Время обновления
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_client_client_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{17}
}

func (x *ClientConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientConfig) GetRateLimits() *RateLimits {
	if x != nil {
		return x.RateLimits
	}
	return nil
}

func (x *ClientConfig) GetAllowedSources() []string {
	if x != nil {
		return x.AllowedSources
	}
	return nil
}

func (x *ClientConfig) GetBlockedDestinations() []string {
	if x != nil {
		return x.BlockedDestinations
	}
	return nil
}

func (x *ClientConfig) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *ClientConfig) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// RateLimits представляет rate limits клиента
type RateLimits struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MessagesPerSecond int32                  `protobuf:"varint,1,opt,name=messages_per_second,json=messagesPerSecond,proto3" json:"messages_per_second,omitempty"` // Сообщений в секунду
	MessagesPerMinute int32                  `protobuf:"varint,2,opt,name=messages_per_minute,json=messagesPerMinute,proto3" json:"messages_per_minute,omitempty"` // Сообщений в минуту
	MessagesPerHour   int32                  `protobuf:"varint,3,opt,name=messages_per_hour,json=messagesPerHour,proto3" json:"messages_per_hour,omitempty"`       // Сообщений в час
	MessagesPerDay    int32                  `protobuf:"varint,4,opt,name=messages_per_day,json=messagesPerDay,proto3" json:"messages_per_day,omitempty"`          // Сообщений в день
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RateLimits) Reset() {
	*x = RateLimits{}
	mi := &file_client_client_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimits) ProtoMessage() {}

func (x *RateLimits) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimits.ProtoReflect.Descriptor instead.
func (*RateLimits) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{18}
}

func (x *RateLimits) GetMessagesPerSecond() int32 {
	if x != nil {
		return x.MessagesPerSecond
	}
	return 0
}

func (x *RateLimits) GetMessagesPerMinute() int32 {
	if x != nil {
		return x.MessagesPerMinute
	}
	return 0
}

func (x *RateLimits) GetMessagesPerHour() int32 {
	if x != nil {
		return x.MessagesPerHour
	}
	return 0
}

func (x *RateLimits) GetMessagesPerDay() int32 {
	if x != nil {
		return x.MessagesPerDay
	}
	return 0
}

var File_client_client_proto protoreflect.FileDescriptor

const file_client_client_proto_rawDesc = "" +
	"\n" +
	"\x13client/client.proto\x12\tclient.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x02\n" +
	"\x13CreateClientRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12%\n" +
	"\x0econtact_person\x18\x03 \x01(\tR\rcontactPerson\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12H\n" +
	"\bmetadata\x18\x06 \x03(\v2,.client.v1.CreateClientRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x14CreateClientResponse\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb8\x02\n" +
	"\x13UpdateClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12%\n" +
	"\x0econtact_person\x18\x04 \x01(\tR\rcontactPerson\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x12H\n" +
	"\bmetadata\x18\a \x03(\v2,.client.v1.UpdateClientRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x14UpdateClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x10GetClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"B\n" +
	"\x11GetClientResponse\x12-\n" +
	"\x06client\x18\x01 \x01(\v2\x15.client.v1.ClientInfoR\x06client\"{\n" +
	"\x12ListClientsRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\\\n" +
	"\x13ListClientsResponse\x12/\n" +
	"\aclients\x18\x01 \x03(\v2\x15.client.v1.ClientInfoR\aclients\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"2\n" +
	"\x13DeleteClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"0\n" +
	"\x14DeleteClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x16GetClientConfigRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"J\n" +
	"\x17GetClientConfigResponse\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.client.v1.ClientConfigR\x06config\"i\n" +
	"\x19UpdateClientConfigRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.client.v1.ClientConfigR\x06config\"6\n" +
	"\x1aUpdateClientConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"t\n" +
	"\x1dUpdateClientRateLimitsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x126\n" +
	"\vrate_limits\x18\x02 \x01(\v2\x15.client.v1.RateLimitsR\n" +
	"rateLimits\":\n" +
	"\x1eUpdateClientRateLimitsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd4\x03\n" +
	"\n" +
	"ClientInfo\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12%\n" +
	"\x0econtact_person\x18\x04 \x01(\tR\rcontactPerson\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active\x126\n" +
	"\vrate_limits\x18\a \x01(\v2\x15.client.v1.RateLimitsR\n" +
	"rateLimits\x12?\n" +
	"\bmetadata\x18\b \x03(\v2#.client.v1.ClientInfo.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x02\n" +
	"\fClientConfig\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x126\n" +
	"\vrate_limits\x18\x02 \x01(\v2\x15.client.v1.RateLimitsR\n" +
	"rateLimits\x12'\n" +
	"\x0fallowed_sources\x18\x03 \x03(\tR\x0eallowedSources\x121\n" +
	"\x14blocked_destinations\x18\x04 \x03(\tR\x13blockedDestinations\x12A\n" +
	"\bsettings\x18\x05 \x03(\v2%.client.v1.ClientConfig.SettingsEntryR\bsettings\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x01\n" +
	"\n" +
	"RateLimits\x12.\n" +
	"\x13messages_per_second\x18\x01 \x01(\x05R\x11messagesPerSecond\x12.\n" +
	"\x13messages_per_minute\x18\x02 \x01(\x05R\x11messagesPerMinute\x12*\n" +
	"\x11messages_per_hour\x18\x03 \x01(\x05R\x0fmessagesPerHour\x12(\n" +
	"\x10messages_per_day\x18\x04 \x01(\x05R\x0emessagesPerDay2\xc4\x05\n" +
	"\rClientService\x12O\n" +
	"\fCreateClient\x12\x1e.client.v1.CreateClientRequest\x1a\x1f.client.v1.CreateClientResponse\x12O\n" +
	"\fUpdateClient\x12\x1e.client.v1.UpdateClientRequest\x1a\x1f.client.v1.UpdateClientResponse\x12F\n" +
	"\tGetClient\x12\x1b.client.v1.GetClientRequest\x1a\x1c.client.v1.GetClientResponse\x12L\n" +
	"\vListClients\x12\x1d.client.v1.ListClientsRequest\x1a\x1e.client.v1.ListClientsResponse\x12O\n" +
	"\fDeleteClient\x12\x1e.client.v1.DeleteClientRequest\x1a\x1f.client.v1.DeleteClientResponse\x12X\n" +
	"\x0fGetClientConfig\x12!.client.v1.GetClientConfigRequest\x1a\".client.v1.GetClientConfigResponse\x12a\n" +
	"\x12UpdateClientConfig\x12$.client.v1.UpdateClientConfigRequest\x1a%.client.v1.UpdateClientConfigResponse\x12m\n" +
	"\x16UpdateClientRateLimits\x12(.client.v1.UpdateClientRateLimitsRequest\x1a).client.v1.UpdateClientRateLimitsResponseB7Z5github.com/smpp-server/smpp-server/api/proto/clientv1b\x06proto3"

var (
	file_client_client_proto_rawDescOnce sync.Once
	file_client_client_proto_rawDescData []byte
)

func file_client_client_proto_rawDescGZIP() []byte {
	file_client_client_proto_rawDescOnce.Do(func() {
		file_client_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_client_proto_rawDesc), len(file_client_client_proto_rawDesc)))
	})
	return file_client_client_proto_rawDescData
}

var file_client_client_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_client_client_proto_goTypes = []any{
	(*CreateClientRequest)(nil),            // 0: client.v1.CreateClientRequest
	(*CreateClientResponse)(nil),           // 1: client.v1.CreateClientResponse
	(*UpdateClientRequest)(nil),            // 2: client.v1.UpdateClientRequest
	(*UpdateClientResponse)(nil),           // 3: client.v1.UpdateClientResponse
	(*GetClientRequest)(nil),               // 4: client.v1.GetClientRequest
	(*GetClientResponse)(nil),              // 5: client.v1.GetClientResponse
	(*ListClientsRequest)(nil),             // 6: client.v1.ListClientsRequest
	(*ListClientsResponse)(nil),            // 7: client.v1.ListClientsResponse
	(*DeleteClientRequest)(nil),            // 8: client.v1.DeleteClientRequest
	(*DeleteClientResponse)(nil),           // 9: client.v1.DeleteClientResponse
	(*GetClientConfigRequest)(nil),         // 10: client.v1.GetClientConfigRequest
	(*GetClientConfigResponse)(nil),        // 11: client.v1.GetClientConfigResponse
	(*UpdateClientConfigRequest)(nil),      // 12: client.v1.UpdateClientConfigRequest
	(*UpdateClientConfigResponse)(nil),     // 13: client.v1.UpdateClientConfigResponse
	(*UpdateClientRateLimitsRequest)(nil),  // 14: client.v1.UpdateClientRateLimitsRequest
	(*UpdateClientRateLimitsResponse)(nil), // 15: client.v1.UpdateClientRateLimitsResponse
	(*ClientInfo)(nil),                     // 16: client.v1.ClientInfo
	(*ClientConfig)(nil),                   // 17: client.v1.ClientConfig
	(*RateLimits)(nil),                     // 18: client.v1.RateLimits
	nil,                                    // 19: client.v1.CreateClientRequest.MetadataEntry
	nil,                                    // 20: client.v1.UpdateClientRequest.MetadataEntry
	nil,                                    // 21: client.v1.ClientInfo.MetadataEntry
	nil,                                    // 22: client.v1.ClientConfig.SettingsEntry
	(*timestamppb.Timestamp)(nil),          // 23: google.protobuf.Timestamp
}
var file_client_client_proto_depIdxs = []int32{
	19, // 0: client.v1.CreateClientRequest.metadata:type_name -> client.v1.CreateClientRequest.MetadataEntry
	23, // 1: client.v1.CreateClientResponse.created_at:type_name -> google.protobuf.Timestamp
	20, // 2: client.v1.UpdateClientRequest.metadata:type_name -> client.v1.UpdateClientRequest.MetadataEntry
	16, // 3: client.v1.GetClientResponse.client:type_name -> client.v1.ClientInfo
	16, // 4: client.v1.ListClientsResponse.clients:type_name -> client.v1.ClientInfo
	17, // 5: client.v1.GetClientConfigResponse.config:type_name -> client.v1.ClientConfig
	17, // 6: client.v1.UpdateClientConfigRequest.config:type_name -> client.v1.ClientConfig
	18, // 7: client.v1.UpdateClientRateLimitsRequest.rate_limits:type_name -> client.v1.RateLimits
	18, // 8: client.v1.ClientInfo.rate_limits:type_name -> client.v1.RateLimits
	21, // 9: client.v1.ClientInfo.metadata:type_name -> client.v1.ClientInfo.MetadataEntry
	23, // 10: client.v1.ClientInfo.created_at:type_name -> google.protobuf.Timestamp
	23, // 11: client.v1.ClientInfo.updated_at:type_name -> google.protobuf.Timestamp
	18, // 12: client.v1.ClientConfig.rate_limits:type_name -> client.v1.RateLimits
	22, // 13: client.v1.ClientConfig.settings:type_name -> client.v1.ClientConfig.SettingsEntry
	23, // 14: client.v1.ClientConfig.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 15: client.v1.ClientService.CreateClient:input_type -> client.v1.CreateClientRequest
	2,  // 16: client.v1.ClientService.UpdateClient:input_type -> client.v1.UpdateClientRequest
	4,  // 17: client.v1.ClientService.GetClient:input_type -> client.v1.GetClientRequest
	6,  // 18: client.v1.ClientService.ListClients:input_type -> client.v1.ListClientsRequest
	8,  // 19: client.v1.ClientService.DeleteClient:input_type -> client.v1.DeleteClientRequest
	10, // 20: client.v1.ClientService.GetClientConfig:input_type -> client.v1.GetClientConfigRequest
	12, // 21: client.v1.ClientService.UpdateClientConfig:input_type -> client.v1.UpdateClientConfigRequest
	14, // 22: client.v1.ClientService.UpdateClientRateLimits:input_type -> client.v1.UpdateClientRateLimitsRequest
	1,  // 23: client.v1.ClientService.CreateClient:output_type -> client.v1.CreateClientResponse
	3,  // 24: client.v1.ClientService.UpdateClient:output_type -> client.v1.UpdateClientResponse
	5,  // 25: client.v1.ClientService.GetClient:output_type -> client.v1.GetClientResponse
	7,  // 26: client.v1.ClientService.ListClients:output_type -> client.v1.ListClientsResponse
	9,  // 27: client.v1.ClientService.DeleteClient:output_type -> client.v1.DeleteClientResponse
	11, // 28: client.v1.ClientService.GetClientConfig:output_type -> client.v1.GetClientConfigResponse
	13, // 29: client.v1.ClientService.UpdateClientConfig:output_type -> client.v1.UpdateClientConfigResponse
	15, // 30: client.v1.ClientService.UpdateClientRateLimits:output_type -> client.v1.UpdateClientRateLimitsResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_client_client_proto_init() }
func file_client_client_proto_init() {
	if File_client_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_client_proto_rawDesc), len(file_client_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_client_proto_goTypes,
		DependencyIndexes: file_client_client_proto_depIdxs,
		MessageInfos:      file_client_client_proto_msgTypes,
	}.Build()
	File_client_client_proto = out.File
	file_client_client_proto_goTypes = nil
	file_client_client_proto_depIdxs = nil
}
