// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: cascade/cascade.proto

package cascadev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CascadeService_CreateDelivery_FullMethodName   = "/cascade.v1.CascadeService/CreateDelivery"
	CascadeService_GetDelivery_FullMethodName      = "/cascade.v1.CascadeService/GetDelivery"
	CascadeService_ListDeliveries_FullMethodName   = "/cascade.v1.CascadeService/ListDeliveries"
	CascadeService_GetDeliveryStats_FullMethodName = "/cascade.v1.CascadeService/GetDeliveryStats"
)

// CascadeServiceClient is the client API for CascadeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CascadeServiceClient interface {
	CreateDelivery(ctx context.Context, in *CreateDeliveryRequest, opts ...grpc.CallOption) (*DeliveryResponse, error)
	GetDelivery(ctx context.Context, in *GetDeliveryRequest, opts ...grpc.CallOption) (*DeliveryResponse, error)
	ListDeliveries(ctx context.Context, in *ListDeliveriesRequest, opts ...grpc.CallOption) (*ListDeliveriesResponse, error)
	GetDeliveryStats(ctx context.Context, in *GetDeliveryStatsRequest, opts ...grpc.CallOption) (*DeliveryStatsResponse, error)
}

type cascadeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCascadeServiceClient(cc grpc.ClientConnInterface) CascadeServiceClient {
	return &cascadeServiceClient{cc}
}

func (c *cascadeServiceClient) CreateDelivery(ctx context.Context, in *CreateDeliveryRequest, opts ...grpc.CallOption) (*DeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryResponse)
	err := c.cc.Invoke(ctx, CascadeService_CreateDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cascadeServiceClient) GetDelivery(ctx context.Context, in *GetDeliveryRequest, opts ...grpc.CallOption) (*DeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryResponse)
	err := c.cc.Invoke(ctx, CascadeService_GetDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cascadeServiceClient) ListDeliveries(ctx context.Context, in *ListDeliveriesRequest, opts ...grpc.CallOption) (*ListDeliveriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeliveriesResponse)
	err := c.cc.Invoke(ctx, CascadeService_ListDeliveries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cascadeServiceClient) GetDeliveryStats(ctx context.Context, in *GetDeliveryStatsRequest, opts ...grpc.CallOption) (*DeliveryStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryStatsResponse)
	err := c.cc.Invoke(ctx, CascadeService_GetDeliveryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CascadeServiceServer is the server API for CascadeService service.
// All implementations must embed UnimplementedCascadeServiceServer
// for forward compatibility.
type CascadeServiceServer interface {
	CreateDelivery(context.Context, *CreateDeliveryRequest) (*DeliveryResponse, error)
	GetDelivery(context.Context, *GetDeliveryRequest) (*DeliveryResponse, error)
	ListDeliveries(context.Context, *ListDeliveriesRequest) (*ListDeliveriesResponse, error)
	GetDeliveryStats(context.Context, *GetDeliveryStatsRequest) (*DeliveryStatsResponse, error)
	mustEmbedUnimplementedCascadeServiceServer()
}

// UnimplementedCascadeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCascadeServiceServer struct{}

func (UnimplementedCascadeServiceServer) CreateDelivery(context.Context, *CreateDeliveryRequest) (*DeliveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDelivery not implemented")
}
func (UnimplementedCascadeServiceServer) GetDelivery(context.Context, *GetDeliveryRequest) (*DeliveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDelivery not implemented")
}
func (UnimplementedCascadeServiceServer) ListDeliveries(context.Context, *ListDeliveriesRequest) (*ListDeliveriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeliveries not implemented")
}
func (UnimplementedCascadeServiceServer) GetDeliveryStats(context.Context, *GetDeliveryStatsRequest) (*DeliveryStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveryStats not implemented")
}
func (UnimplementedCascadeServiceServer) mustEmbedUnimplementedCascadeServiceServer() {}
func (UnimplementedCascadeServiceServer) testEmbeddedByValue()                        {}

// UnsafeCascadeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CascadeServiceServer will
// result in compilation errors.
type UnsafeCascadeServiceServer interface {
	mustEmbedUnimplementedCascadeServiceServer()
}

func RegisterCascadeServiceServer(s grpc.ServiceRegistrar, srv CascadeServiceServer) {
	// If the following call pancis, it indicates UnimplementedCascadeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CascadeService_ServiceDesc, srv)
}

func _CascadeService_CreateDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CascadeServiceServer).CreateDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CascadeService_CreateDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CascadeServiceServer).CreateDelivery(ctx, req.(*CreateDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CascadeService_GetDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CascadeServiceServer).GetDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CascadeService_GetDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CascadeServiceServer).GetDelivery(ctx, req.(*GetDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CascadeService_ListDeliveries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeliveriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CascadeServiceServer).ListDeliveries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CascadeService_ListDeliveries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CascadeServiceServer).ListDeliveries(ctx, req.(*ListDeliveriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CascadeService_GetDeliveryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CascadeServiceServer).GetDeliveryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CascadeService_GetDeliveryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CascadeServiceServer).GetDeliveryStats(ctx, req.(*GetDeliveryStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CascadeService_ServiceDesc is the grpc.ServiceDesc for CascadeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CascadeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cascade.v1.CascadeService",
	HandlerType: (*CascadeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDelivery",
			Handler:    _CascadeService_CreateDelivery_Handler,
		},
		{
			MethodName: "GetDelivery",
			Handler:    _CascadeService_GetDelivery_Handler,
		},
		{
			MethodName: "ListDeliveries",
			Handler:    _CascadeService_ListDeliveries_Handler,
		},
		{
			MethodName: "GetDeliveryStats",
			Handler:    _CascadeService_GetDeliveryStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cascade/cascade.proto",
}

const (
	ChannelAdminService_ListChannels_FullMethodName  = "/cascade.v1.ChannelAdminService/ListChannels"
	ChannelAdminService_GetChannel_FullMethodName    = "/cascade.v1.ChannelAdminService/GetChannel"
	ChannelAdminService_CreateChannel_FullMethodName = "/cascade.v1.ChannelAdminService/CreateChannel"
	ChannelAdminService_UpdateChannel_FullMethodName = "/cascade.v1.ChannelAdminService/UpdateChannel"
	ChannelAdminService_ToggleChannel_FullMethodName = "/cascade.v1.ChannelAdminService/ToggleChannel"
)

// ChannelAdminServiceClient is the client API for ChannelAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChannelAdminServiceClient interface {
	ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ListChannelsResponse, error)
	GetChannel(ctx context.Context, in *GetChannelRequest, opts ...grpc.CallOption) (*ChannelResponse, error)
	CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*ChannelResponse, error)
	UpdateChannel(ctx context.Context, in *UpdateChannelRequest, opts ...grpc.CallOption) (*ChannelResponse, error)
	ToggleChannel(ctx context.Context, in *ToggleChannelRequest, opts ...grpc.CallOption) (*ChannelResponse, error)
}

type channelAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelAdminServiceClient(cc grpc.ClientConnInterface) ChannelAdminServiceClient {
	return &channelAdminServiceClient{cc}
}

func (c *channelAdminServiceClient) ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ListChannelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChannelsResponse)
	err := c.cc.Invoke(ctx, ChannelAdminService_ListChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAdminServiceClient) GetChannel(ctx context.Context, in *GetChannelRequest, opts ...grpc.CallOption) (*ChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelResponse)
	err := c.cc.Invoke(ctx, ChannelAdminService_GetChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAdminServiceClient) CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*ChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelResponse)
	err := c.cc.Invoke(ctx, ChannelAdminService_CreateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAdminServiceClient) UpdateChannel(ctx context.Context, in *UpdateChannelRequest, opts ...grpc.CallOption) (*ChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelResponse)
	err := c.cc.Invoke(ctx, ChannelAdminService_UpdateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAdminServiceClient) ToggleChannel(ctx context.Context, in *ToggleChannelRequest, opts ...grpc.CallOption) (*ChannelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelResponse)
	err := c.cc.Invoke(ctx, ChannelAdminService_ToggleChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelAdminServiceServer is the server API for ChannelAdminService service.
// All implementations must embed UnimplementedChannelAdminServiceServer
// for forward compatibility.
type ChannelAdminServiceServer interface {
	ListChannels(context.Context, *ListChannelsRequest) (*ListChannelsResponse, error)
	GetChannel(context.Context, *GetChannelRequest) (*ChannelResponse, error)
	CreateChannel(context.Context, *CreateChannelRequest) (*ChannelResponse, error)
	UpdateChannel(context.Context, *UpdateChannelRequest) (*ChannelResponse, error)
	ToggleChannel(context.Context, *ToggleChannelRequest) (*ChannelResponse, error)
	mustEmbedUnimplementedChannelAdminServiceServer()
}

// UnimplementedChannelAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelAdminServiceServer struct{}

func (UnimplementedChannelAdminServiceServer) ListChannels(context.Context, *ListChannelsRequest) (*ListChannelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChannels not implemented")
}
func (UnimplementedChannelAdminServiceServer) GetChannel(context.Context, *GetChannelRequest) (*ChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannel not implemented")
}
func (UnimplementedChannelAdminServiceServer) CreateChannel(context.Context, *CreateChannelRequest) (*ChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChannel not implemented")
}
func (UnimplementedChannelAdminServiceServer) UpdateChannel(context.Context, *UpdateChannelRequest) (*ChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChannel not implemented")
}
func (UnimplementedChannelAdminServiceServer) ToggleChannel(context.Context, *ToggleChannelRequest) (*ChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleChannel not implemented")
}
func (UnimplementedChannelAdminServiceServer) mustEmbedUnimplementedChannelAdminServiceServer() {}
func (UnimplementedChannelAdminServiceServer) testEmbeddedByValue()                             {}

// UnsafeChannelAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelAdminServiceServer will
// result in compilation errors.
type UnsafeChannelAdminServiceServer interface {
	mustEmbedUnimplementedChannelAdminServiceServer()
}

func RegisterChannelAdminServiceServer(s grpc.ServiceRegistrar, srv ChannelAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedChannelAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChannelAdminService_ServiceDesc, srv)
}

func _ChannelAdminService_ListChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAdminServiceServer).ListChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelAdminService_ListChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAdminServiceServer).ListChannels(ctx, req.(*ListChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAdminService_GetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAdminServiceServer).GetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelAdminService_GetChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAdminServiceServer).GetChannel(ctx, req.(*GetChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAdminService_CreateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAdminServiceServer).CreateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelAdminService_CreateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAdminServiceServer).CreateChannel(ctx, req.(*CreateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAdminService_UpdateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAdminServiceServer).UpdateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelAdminService_UpdateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAdminServiceServer).UpdateChannel(ctx, req.(*UpdateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAdminService_ToggleChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAdminServiceServer).ToggleChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelAdminService_ToggleChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAdminServiceServer).ToggleChannel(ctx, req.(*ToggleChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChannelAdminService_ServiceDesc is the grpc.ServiceDesc for ChannelAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cascade.v1.ChannelAdminService",
	HandlerType: (*ChannelAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListChannels",
			Handler:    _ChannelAdminService_ListChannels_Handler,
		},
		{
			MethodName: "GetChannel",
			Handler:    _ChannelAdminService_GetChannel_Handler,
		},
		{
			MethodName: "CreateChannel",
			Handler:    _ChannelAdminService_CreateChannel_Handler,
		},
		{
			MethodName: "UpdateChannel",
			Handler:    _ChannelAdminService_UpdateChannel_Handler,
		},
		{
			MethodName: "ToggleChannel",
			Handler:    _ChannelAdminService_ToggleChannel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cascade/cascade.proto",
}

const (
	StrategyAdminService_ListStrategies_FullMethodName               = "/cascade.v1.StrategyAdminService/ListStrategies"
	StrategyAdminService_GetStrategy_FullMethodName                  = "/cascade.v1.StrategyAdminService/GetStrategy"
	StrategyAdminService_CreateStrategy_FullMethodName               = "/cascade.v1.StrategyAdminService/CreateStrategy"
	StrategyAdminService_UpdateStrategy_FullMethodName               = "/cascade.v1.StrategyAdminService/UpdateStrategy"
	StrategyAdminService_DeleteStrategy_FullMethodName               = "/cascade.v1.StrategyAdminService/DeleteStrategy"
	StrategyAdminService_GetOperatorChannelSupport_FullMethodName    = "/cascade.v1.StrategyAdminService/GetOperatorChannelSupport"
	StrategyAdminService_UpdateOperatorChannelSupport_FullMethodName = "/cascade.v1.StrategyAdminService/UpdateOperatorChannelSupport"
)

// StrategyAdminServiceClient is the client API for StrategyAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrategyAdminServiceClient interface {
	ListStrategies(ctx context.Context, in *ListStrategiesRequest, opts ...grpc.CallOption) (*ListStrategiesResponse, error)
	GetStrategy(ctx context.Context, in *GetStrategyRequest, opts ...grpc.CallOption) (*StrategyResponse, error)
	CreateStrategy(ctx context.Context, in *CreateStrategyRequest, opts ...grpc.CallOption) (*StrategyResponse, error)
	UpdateStrategy(ctx context.Context, in *UpdateStrategyRequest, opts ...grpc.CallOption) (*StrategyResponse, error)
	DeleteStrategy(ctx context.Context, in *DeleteStrategyRequest, opts ...grpc.CallOption) (*DeleteStrategyResponse, error)
	GetOperatorChannelSupport(ctx context.Context, in *GetOCSRequest, opts ...grpc.CallOption) (*GetOCSResponse, error)
	UpdateOperatorChannelSupport(ctx context.Context, in *UpdateOCSRequest, opts ...grpc.CallOption) (*UpdateOCSResponse, error)
}

type strategyAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategyAdminServiceClient(cc grpc.ClientConnInterface) StrategyAdminServiceClient {
	return &strategyAdminServiceClient{cc}
}

func (c *strategyAdminServiceClient) ListStrategies(ctx context.Context, in *ListStrategiesRequest, opts ...grpc.CallOption) (*ListStrategiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStrategiesResponse)
	err := c.cc.Invoke(ctx, StrategyAdminService_ListStrategies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyAdminServiceClient) GetStrategy(ctx context.Context, in *GetStrategyRequest, opts ...grpc.CallOption) (*StrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyResponse)
	err := c.cc.Invoke(ctx, StrategyAdminService_GetStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyAdminServiceClient) CreateStrategy(ctx context.Context, in *CreateStrategyRequest, opts ...grpc.CallOption) (*StrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyResponse)
	err := c.cc.Invoke(ctx, StrategyAdminService_CreateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyAdminServiceClient) UpdateStrategy(ctx context.Context, in *UpdateStrategyRequest, opts ...grpc.CallOption) (*StrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyResponse)
	err := c.cc.Invoke(ctx, StrategyAdminService_UpdateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyAdminServiceClient) DeleteStrategy(ctx context.Context, in *DeleteStrategyRequest, opts ...grpc.CallOption) (*DeleteStrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStrategyResponse)
	err := c.cc.Invoke(ctx, StrategyAdminService_DeleteStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyAdminServiceClient) GetOperatorChannelSupport(ctx context.Context, in *GetOCSRequest, opts ...grpc.CallOption) (*GetOCSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOCSResponse)
	err := c.cc.Invoke(ctx, StrategyAdminService_GetOperatorChannelSupport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyAdminServiceClient) UpdateOperatorChannelSupport(ctx context.Context, in *UpdateOCSRequest, opts ...grpc.CallOption) (*UpdateOCSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOCSResponse)
	err := c.cc.Invoke(ctx, StrategyAdminService_UpdateOperatorChannelSupport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyAdminServiceServer is the server API for StrategyAdminService service.
// All implementations must embed UnimplementedStrategyAdminServiceServer
// for forward compatibility.
type StrategyAdminServiceServer interface {
	ListStrategies(context.Context, *ListStrategiesRequest) (*ListStrategiesResponse, error)
	GetStrategy(context.Context, *GetStrategyRequest) (*StrategyResponse, error)
	CreateStrategy(context.Context, *CreateStrategyRequest) (*StrategyResponse, error)
	UpdateStrategy(context.Context, *UpdateStrategyRequest) (*StrategyResponse, error)
	DeleteStrategy(context.Context, *DeleteStrategyRequest) (*DeleteStrategyResponse, error)
	GetOperatorChannelSupport(context.Context, *GetOCSRequest) (*GetOCSResponse, error)
	UpdateOperatorChannelSupport(context.Context, *UpdateOCSRequest) (*UpdateOCSResponse, error)
	mustEmbedUnimplementedStrategyAdminServiceServer()
}

// UnimplementedStrategyAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStrategyAdminServiceServer struct{}

func (UnimplementedStrategyAdminServiceServer) ListStrategies(context.Context, *ListStrategiesRequest) (*ListStrategiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStrategies not implemented")
}
func (UnimplementedStrategyAdminServiceServer) GetStrategy(context.Context, *GetStrategyRequest) (*StrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStrategy not implemented")
}
func (UnimplementedStrategyAdminServiceServer) CreateStrategy(context.Context, *CreateStrategyRequest) (*StrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStrategy not implemented")
}
func (UnimplementedStrategyAdminServiceServer) UpdateStrategy(context.Context, *UpdateStrategyRequest) (*StrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStrategy not implemented")
}
func (UnimplementedStrategyAdminServiceServer) DeleteStrategy(context.Context, *DeleteStrategyRequest) (*DeleteStrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStrategy not implemented")
}
func (UnimplementedStrategyAdminServiceServer) GetOperatorChannelSupport(context.Context, *GetOCSRequest) (*GetOCSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperatorChannelSupport not implemented")
}
func (UnimplementedStrategyAdminServiceServer) UpdateOperatorChannelSupport(context.Context, *UpdateOCSRequest) (*UpdateOCSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOperatorChannelSupport not implemented")
}
func (UnimplementedStrategyAdminServiceServer) mustEmbedUnimplementedStrategyAdminServiceServer() {}
func (UnimplementedStrategyAdminServiceServer) testEmbeddedByValue()                              {}

// UnsafeStrategyAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrategyAdminServiceServer will
// result in compilation errors.
type UnsafeStrategyAdminServiceServer interface {
	mustEmbedUnimplementedStrategyAdminServiceServer()
}

func RegisterStrategyAdminServiceServer(s grpc.ServiceRegistrar, srv StrategyAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedStrategyAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StrategyAdminService_ServiceDesc, srv)
}

func _StrategyAdminService_ListStrategies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStrategiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyAdminServiceServer).ListStrategies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyAdminService_ListStrategies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyAdminServiceServer).ListStrategies(ctx, req.(*ListStrategiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyAdminService_GetStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyAdminServiceServer).GetStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyAdminService_GetStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyAdminServiceServer).GetStrategy(ctx, req.(*GetStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyAdminService_CreateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyAdminServiceServer).CreateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyAdminService_CreateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyAdminServiceServer).CreateStrategy(ctx, req.(*CreateStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyAdminService_UpdateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyAdminServiceServer).UpdateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyAdminService_UpdateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyAdminServiceServer).UpdateStrategy(ctx, req.(*UpdateStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyAdminService_DeleteStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyAdminServiceServer).DeleteStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyAdminService_DeleteStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyAdminServiceServer).DeleteStrategy(ctx, req.(*DeleteStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyAdminService_GetOperatorChannelSupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOCSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyAdminServiceServer).GetOperatorChannelSupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyAdminService_GetOperatorChannelSupport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyAdminServiceServer).GetOperatorChannelSupport(ctx, req.(*GetOCSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyAdminService_UpdateOperatorChannelSupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOCSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyAdminServiceServer).UpdateOperatorChannelSupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyAdminService_UpdateOperatorChannelSupport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyAdminServiceServer).UpdateOperatorChannelSupport(ctx, req.(*UpdateOCSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StrategyAdminService_ServiceDesc is the grpc.ServiceDesc for StrategyAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StrategyAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cascade.v1.StrategyAdminService",
	HandlerType: (*StrategyAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListStrategies",
			Handler:    _StrategyAdminService_ListStrategies_Handler,
		},
		{
			MethodName: "GetStrategy",
			Handler:    _StrategyAdminService_GetStrategy_Handler,
		},
		{
			MethodName: "CreateStrategy",
			Handler:    _StrategyAdminService_CreateStrategy_Handler,
		},
		{
			MethodName: "UpdateStrategy",
			Handler:    _StrategyAdminService_UpdateStrategy_Handler,
		},
		{
			MethodName: "DeleteStrategy",
			Handler:    _StrategyAdminService_DeleteStrategy_Handler,
		},
		{
			MethodName: "GetOperatorChannelSupport",
			Handler:    _StrategyAdminService_GetOperatorChannelSupport_Handler,
		},
		{
			MethodName: "UpdateOperatorChannelSupport",
			Handler:    _StrategyAdminService_UpdateOperatorChannelSupport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cascade/cascade.proto",
}
