// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: sms.proto

package smsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendSMSRequest представляет запрос на отправку SMS
type SendSMSRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Source             string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`                                                    // Отправитель
	Destination        string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`                                          // Получатель
	Text               string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`                                                        // Текст сообщения
	ExternalId         string                 `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`                          // Внешний ID (опционально)
	Priority           int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                                               // Приоритет (0-3)
	RegisteredDelivery bool                   `protobuf:"varint,6,opt,name=registered_delivery,json=registeredDelivery,proto3" json:"registered_delivery,omitempty"` // Требовать DLR
	ValidityPeriod     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=validity_period,json=validityPeriod,proto3" json:"validity_period,omitempty"`              // Срок действия (опционально)
	ServiceType        string                 `protobuf:"bytes,8,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`                       // Тип сервиса (опционально)
	SourceAddrTon      int32                  `protobuf:"varint,9,opt,name=source_addr_ton,json=sourceAddrTon,proto3" json:"source_addr_ton,omitempty"`              // TON отправителя (опционально)
	SourceAddrNpi      int32                  `protobuf:"varint,10,opt,name=source_addr_npi,json=sourceAddrNpi,proto3" json:"source_addr_npi,omitempty"`             // NPI отправителя (опционально)
	DestAddrTon        int32                  `protobuf:"varint,11,opt,name=dest_addr_ton,json=destAddrTon,proto3" json:"dest_addr_ton,omitempty"`                   // TON получателя (опционально)
	DestAddrNpi        int32                  `protobuf:"varint,12,opt,name=dest_addr_npi,json=destAddrNpi,proto3" json:"dest_addr_npi,omitempty"`                   // NPI получателя (опционально)
	DataCoding         int32                  `protobuf:"varint,13,opt,name=data_coding,json=dataCoding,proto3" json:"data_coding,omitempty"`                        // Кодировка данных (опционально)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SendSMSRequest) Reset() {
	*x = SendSMSRequest{}
	mi := &file_sms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMSRequest) ProtoMessage() {}

func (x *SendSMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMSRequest.ProtoReflect.Descriptor instead.
func (*SendSMSRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{0}
}

func (x *SendSMSRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SendSMSRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SendSMSRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendSMSRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *SendSMSRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SendSMSRequest) GetRegisteredDelivery() bool {
	if x != nil {
		return x.RegisteredDelivery
	}
	return false
}

func (x *SendSMSRequest) GetValidityPeriod() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidityPeriod
	}
	return nil
}

func (x *SendSMSRequest) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *SendSMSRequest) GetSourceAddrTon() int32 {
	if x != nil {
		return x.SourceAddrTon
	}
	return 0
}

func (x *SendSMSRequest) GetSourceAddrNpi() int32 {
	if x != nil {
		return x.SourceAddrNpi
	}
	return 0
}

func (x *SendSMSRequest) GetDestAddrTon() int32 {
	if x != nil {
		return x.DestAddrTon
	}
	return 0
}

func (x *SendSMSRequest) GetDestAddrNpi() int32 {
	if x != nil {
		return x.DestAddrNpi
	}
	return 0
}

func (x *SendSMSRequest) GetDataCoding() int32 {
	if x != nil {
		return x.DataCoding
	}
	return 0
}

// SendSMSResponse представляет ответ на отправку SMS
type SendSMSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // ID сообщения
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                        // Статус (queued, sent, failed)
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                          // Ошибка (если есть)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSMSResponse) Reset() {
	*x = SendSMSResponse{}
	mi := &file_sms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMSResponse) ProtoMessage() {}

func (x *SendSMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMSResponse.ProtoReflect.Descriptor instead.
func (*SendSMSResponse) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{1}
}

func (x *SendSMSResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendSMSResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendSMSResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SendBatchRequest представляет запрос на пакетную отправку SMS
type SendBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*SendSMSRequest      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"` // Список сообщений
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchRequest) Reset() {
	*x = SendBatchRequest{}
	mi := &file_sms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchRequest) ProtoMessage() {}

func (x *SendBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchRequest.ProtoReflect.Descriptor instead.
func (*SendBatchRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{2}
}

func (x *SendBatchRequest) GetMessages() []*SendSMSRequest {
	if x != nil {
		return x.Messages
	}
	return nil
}

// SendBatchResponse представляет ответ на пакетную отправку
type SendBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SendSMSResponse     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`                                // Результаты для каждого сообщения
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // Количество успешных
	FailedCount   int32                  `protobuf:"varint,3,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`    // Количество неудачных
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBatchResponse) Reset() {
	*x = SendBatchResponse{}
	mi := &file_sms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBatchResponse) ProtoMessage() {}

func (x *SendBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBatchResponse.ProtoReflect.Descriptor instead.
func (*SendBatchResponse) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{3}
}

func (x *SendBatchResponse) GetResults() []*SendSMSResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SendBatchResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *SendBatchResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

// GetStatusRequest представляет запрос на получение статуса
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // ID сообщения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_sms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatusRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// GetStatusResponse представляет ответ со статусом
type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`               // ID сообщения
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                      // Статус (pending, queued, sent, delivered, failed, expired, rejected)
	StatusMessage string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`   // Сообщение о статусе
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`               // Время создания
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`         // Время отправки (опционально)
	DeliveredAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`         // Время доставки (опционально)
	FailedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`                  // Время ошибки (опционально)
	SmppMessageId string                 `protobuf:"bytes,8,opt,name=smpp_message_id,json=smppMessageId,proto3" json:"smpp_message_id,omitempty"` // SMPP message ID (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_sms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *GetStatusResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetStatusResponse) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *GetStatusResponse) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *GetStatusResponse) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

func (x *GetStatusResponse) GetSmppMessageId() string {
	if x != nil {
		return x.SmppMessageId
	}
	return ""
}

// StreamDLRRequest представляет запрос на поток DLR
type StreamDLRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageIds    []string               `protobuf:"bytes,1,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"` // ID сообщений для отслеживания (пусто = все)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDLRRequest) Reset() {
	*x = StreamDLRRequest{}
	mi := &file_sms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDLRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDLRRequest) ProtoMessage() {}

func (x *StreamDLRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDLRRequest.ProtoReflect.Descriptor instead.
func (*StreamDLRRequest) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{6}
}

func (x *StreamDLRRequest) GetMessageIds() []string {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

// DLRUpdate представляет обновление DLR
type DLRUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`               // ID сообщения
	SmppMessageId string                 `protobuf:"bytes,2,opt,name=smpp_message_id,json=smppMessageId,proto3" json:"smpp_message_id,omitempty"` // SMPP message ID
	Stat          string                 `protobuf:"bytes,3,opt,name=stat,proto3" json:"stat,omitempty"`                                          // Статус доставки (DELIVRD, UNDELIV, EXPIRED, etc.)
	DoneDate      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=done_date,json=doneDate,proto3" json:"done_date,omitempty"`                  // Время доставки
	Err           int32                  `protobuf:"varint,5,opt,name=err,proto3" json:"err,omitempty"`                                           // Код ошибки (опционально)
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`                                          // Текст ошибки (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DLRUpdate) Reset() {
	*x = DLRUpdate{}
	mi := &file_sms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLRUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLRUpdate) ProtoMessage() {}

func (x *DLRUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_sms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLRUpdate.ProtoReflect.Descriptor instead.
func (*DLRUpdate) Descriptor() ([]byte, []int) {
	return file_sms_proto_rawDescGZIP(), []int{7}
}

func (x *DLRUpdate) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DLRUpdate) GetSmppMessageId() string {
	if x != nil {
		return x.SmppMessageId
	}
	return ""
}

func (x *DLRUpdate) GetStat() string {
	if x != nil {
		return x.Stat
	}
	return ""
}

func (x *DLRUpdate) GetDoneDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DoneDate
	}
	return nil
}

func (x *DLRUpdate) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *DLRUpdate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_sms_proto protoreflect.FileDescriptor

const file_sms_proto_rawDesc = "" +
	"\n" +
	"\tsms.proto\x12\x06sms.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x03\n" +
	"\x0eSendSMSRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1f\n" +
	"\vexternal_id\x18\x04 \x01(\tR\n" +
	"externalId\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12/\n" +
	"\x13registered_delivery\x18\x06 \x01(\bR\x12registeredDelivery\x12C\n" +
	"\x0fvalidity_period\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0evalidityPeriod\x12!\n" +
	"\fservice_type\x18\b \x01(\tR\vserviceType\x12&\n" +
	"\x0fsource_addr_ton\x18\t \x01(\x05R\rsourceAddrTon\x12&\n" +
	"\x0fsource_addr_npi\x18\n" +
	" \x01(\x05R\rsourceAddrNpi\x12\"\n" +
	"\rdest_addr_ton\x18\v \x01(\x05R\vdestAddrTon\x12\"\n" +
	"\rdest_addr_npi\x18\f \x01(\x05R\vdestAddrNpi\x12\x1f\n" +
	"\vdata_coding\x18\r \x01(\x05R\n" +
	"dataCoding\"^\n" +
	"\x0fSendSMSResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"F\n" +
	"\x10SendBatchRequest\x122\n" +
	"\bmessages\x18\x01 \x03(\v2\x16.sms.v1.SendSMSRequestR\bmessages\"\x8e\x01\n" +
	"\x11SendBatchResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.sms.v1.SendSMSResponseR\aresults\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x03 \x01(\x05R\vfailedCount\"1\n" +
	"\x10GetStatusRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\x8b\x03\n" +
	"\x11GetStatusResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fsubmitted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\x12=\n" +
	"\fdelivered_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\x127\n" +
	"\tfailed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAt\x12&\n" +
	"\x0fsmpp_message_id\x18\b \x01(\tR\rsmppMessageId\"3\n" +
	"\x10StreamDLRRequest\x12\x1f\n" +
	"\vmessage_ids\x18\x01 \x03(\tR\n" +
	"messageIds\"\xc5\x01\n" +
	"\tDLRUpdate\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12&\n" +
	"\x0fsmpp_message_id\x18\x02 \x01(\tR\rsmppMessageId\x12\x12\n" +
	"\x04stat\x18\x03 \x01(\tR\x04stat\x127\n" +
	"\tdone_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdoneDate\x12\x10\n" +
	"\x03err\x18\x05 \x01(\x05R\x03err\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text2\x8b\x02\n" +
	"\n" +
	"SMSService\x12:\n" +
	"\aSendSMS\x12\x16.sms.v1.SendSMSRequest\x1a\x17.sms.v1.SendSMSResponse\x12C\n" +
	"\fSendBatchSMS\x12\x18.sms.v1.SendBatchRequest\x1a\x19.sms.v1.SendBatchResponse\x12@\n" +
	"\tGetStatus\x12\x18.sms.v1.GetStatusRequest\x1a\x19.sms.v1.GetStatusResponse\x12:\n" +
	"\tStreamDLR\x12\x18.sms.v1.StreamDLRRequest\x1a\x11.sms.v1.DLRUpdate0\x01B4Z2github.com/smpp-server/smpp-server/api/proto/smsv1b\x06proto3"

var (
	file_sms_proto_rawDescOnce sync.Once
	file_sms_proto_rawDescData []byte
)

func file_sms_proto_rawDescGZIP() []byte {
	file_sms_proto_rawDescOnce.Do(func() {
		file_sms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sms_proto_rawDesc), len(file_sms_proto_rawDesc)))
	})
	return file_sms_proto_rawDescData
}

var file_sms_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sms_proto_goTypes = []any{
	(*SendSMSRequest)(nil),        // 0: sms.v1.SendSMSRequest
	(*SendSMSResponse)(nil),       // 1: sms.v1.SendSMSResponse
	(*SendBatchRequest)(nil),      // 2: sms.v1.SendBatchRequest
	(*SendBatchResponse)(nil),     // 3: sms.v1.SendBatchResponse
	(*GetStatusRequest)(nil),      // 4: sms.v1.GetStatusRequest
	(*GetStatusResponse)(nil),     // 5: sms.v1.GetStatusResponse
	(*StreamDLRRequest)(nil),      // 6: sms.v1.StreamDLRRequest
	(*DLRUpdate)(nil),             // 7: sms.v1.DLRUpdate
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_sms_proto_depIdxs = []int32{
	8,  // 0: sms.v1.SendSMSRequest.validity_period:type_name -> google.protobuf.Timestamp
	0,  // 1: sms.v1.SendBatchRequest.messages:type_name -> sms.v1.SendSMSRequest
	1,  // 2: sms.v1.SendBatchResponse.results:type_name -> sms.v1.SendSMSResponse
	8,  // 3: sms.v1.GetStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	8,  // 4: sms.v1.GetStatusResponse.submitted_at:type_name -> google.protobuf.Timestamp
	8,  // 5: sms.v1.GetStatusResponse.delivered_at:type_name -> google.protobuf.Timestamp
	8,  // 6: sms.v1.GetStatusResponse.failed_at:type_name -> google.protobuf.Timestamp
	8,  // 7: sms.v1.DLRUpdate.done_date:type_name -> google.protobuf.Timestamp
	0,  // 8: sms.v1.SMSService.SendSMS:input_type -> sms.v1.SendSMSRequest
	2,  // 9: sms.v1.SMSService.SendBatchSMS:input_type -> sms.v1.SendBatchRequest
	4,  // 10: sms.v1.SMSService.GetStatus:input_type -> sms.v1.GetStatusRequest
	6,  // 11: sms.v1.SMSService.StreamDLR:input_type -> sms.v1.StreamDLRRequest
	1,  // 12: sms.v1.SMSService.SendSMS:output_type -> sms.v1.SendSMSResponse
	3,  // 13: sms.v1.SMSService.SendBatchSMS:output_type -> sms.v1.SendBatchResponse
	5,  // 14: sms.v1.SMSService.GetStatus:output_type -> sms.v1.GetStatusResponse
	7,  // 15: sms.v1.SMSService.StreamDLR:output_type -> sms.v1.DLRUpdate
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_sms_proto_init() }
func file_sms_proto_init() {
	if File_sms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sms_proto_rawDesc), len(file_sms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sms_proto_goTypes,
		DependencyIndexes: file_sms_proto_depIdxs,
		MessageInfos:      file_sms_proto_msgTypes,
	}.Build()
	File_sms_proto = out.File
	file_sms_proto_goTypes = nil
	file_sms_proto_depIdxs = nil
}
